/*
###############################################################
#  Generated by:      Cadence Innovus 17.11-s080_1
#  OS:                Linux x86_64(Host ID localhost.localdomain)
#  Generated on:      Wed Oct 28 18:22:45 2020
#  Design:            filter
#  Command:           saveNetlist netlist/filter_innovus.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : O-2018.06-SP4
// Date      : Wed Oct 28 16:52:37 2020
/////////////////////////////////////////////////////////////
module filter (
	clk, 
	rst, 
	vin, 
	Din, 
	b0, 
	a1, 
	vout, 
	Dout);
   input clk;
   input rst;
   input vin;
   input [7:0] Din;
   input [7:0] b0;
   input [7:0] a1;
   output vout;
   output [7:0] Dout;

   // Internal wires
   wire FE_OFN3_mult_94_n235;
   wire FE_OFN2_mult_93_n235;
   wire FE_OFN1_mult_93_n242;
   wire FE_OFN0_mult_94_n242;
   wire FE_DBTN5_b0_7;
   wire FE_DBTN4_b0_5;
   wire FE_DBTN3_b0_3;
   wire FE_DBTN2_b0_0;
   wire FE_DBTN1_tmpfb_0;
   wire FE_DBTN0_tmpfb_1;
   wire tmprvin;
   wire n1;
   wire n3;
   wire n4;
   wire n5;
   wire n6;
   wire n7;
   wire n8;
   wire n9;
   wire n10;
   wire n12;
   wire n13;
   wire n14;
   wire n15;
   wire n16;
   wire n17;
   wire n18;
   wire n19;
   wire m2_tmp_9_;
   wire m2_tmp_8_;
   wire m2_tmp_7_;
   wire m2_tmp_14_;
   wire m2_tmp_13_;
   wire m2_tmp_12_;
   wire m2_tmp_11_;
   wire m2_tmp_10_;
   wire ff_tmp_9_;
   wire ff_tmp_8_;
   wire ff_tmp_7_;
   wire ff_tmp_14_;
   wire ff_tmp_13_;
   wire ff_tmp_12_;
   wire ff_tmp_11_;
   wire ff_tmp_10_;
   wire m1_tmp_9_;
   wire m1_tmp_8_;
   wire m1_tmp_7_;
   wire m1_tmp_15_;
   wire m1_tmp_14_;
   wire m1_tmp_13_;
   wire m1_tmp_12_;
   wire m1_tmp_11_;
   wire m1_tmp_10_;
   wire n37;
   wire n41;
   wire n42;
   wire n43;
   wire n44;
   wire n45;
   wire n46;
   wire n47;
   wire n48;
   wire n49;
   wire n50;
   wire n51;
   wire n52;
   wire n53;
   wire n54;
   wire n55;
   wire n56;
   wire n57;
   wire n58;
   wire mult_94_n289;
   wire mult_94_n288;
   wire mult_94_n287;
   wire mult_94_n286;
   wire mult_94_n285;
   wire mult_94_n284;
   wire mult_94_n283;
   wire mult_94_n282;
   wire mult_94_n281;
   wire mult_94_n280;
   wire mult_94_n279;
   wire mult_94_n278;
   wire mult_94_n277;
   wire mult_94_n276;
   wire mult_94_n275;
   wire mult_94_n274;
   wire mult_94_n273;
   wire mult_94_n272;
   wire mult_94_n271;
   wire mult_94_n270;
   wire mult_94_n269;
   wire mult_94_n268;
   wire mult_94_n267;
   wire mult_94_n266;
   wire mult_94_n265;
   wire mult_94_n264;
   wire mult_94_n263;
   wire mult_94_n262;
   wire mult_94_n261;
   wire mult_94_n260;
   wire mult_94_n259;
   wire mult_94_n258;
   wire mult_94_n257;
   wire mult_94_n256;
   wire mult_94_n255;
   wire mult_94_n254;
   wire mult_94_n253;
   wire mult_94_n252;
   wire mult_94_n251;
   wire mult_94_n250;
   wire mult_94_n249;
   wire mult_94_n248;
   wire mult_94_n247;
   wire mult_94_n246;
   wire mult_94_n245;
   wire mult_94_n244;
   wire mult_94_n243;
   wire mult_94_n242;
   wire mult_94_n241;
   wire mult_94_n240;
   wire mult_94_n239;
   wire mult_94_n238;
   wire mult_94_n237;
   wire mult_94_n236;
   wire mult_94_n235;
   wire mult_94_n234;
   wire mult_94_n233;
   wire mult_94_n232;
   wire mult_94_n231;
   wire mult_94_n230;
   wire mult_94_n229;
   wire mult_94_n228;
   wire mult_94_n227;
   wire mult_94_n223;
   wire mult_94_n222;
   wire mult_94_n221;
   wire mult_94_n219;
   wire mult_94_n218;
   wire mult_94_n217;
   wire mult_94_n216;
   wire mult_94_n214;
   wire mult_94_n213;
   wire mult_94_n212;
   wire mult_94_n211;
   wire mult_94_n109;
   wire mult_94_n108;
   wire mult_94_n107;
   wire mult_94_n106;
   wire mult_94_n105;
   wire mult_94_n104;
   wire mult_94_n101;
   wire mult_94_n100;
   wire mult_94_n99;
   wire mult_94_n98;
   wire mult_94_n97;
   wire mult_94_n96;
   wire mult_94_n93;
   wire mult_94_n92;
   wire mult_94_n91;
   wire mult_94_n90;
   wire mult_94_n89;
   wire mult_94_n88;
   wire mult_94_n87;
   wire mult_94_n86;
   wire mult_94_n84;
   wire mult_94_n83;
   wire mult_94_n82;
   wire mult_94_n80;
   wire mult_94_n79;
   wire mult_94_n78;
   wire mult_94_n77;
   wire mult_94_n73;
   wire mult_94_n72;
   wire mult_94_n61;
   wire mult_94_n60;
   wire mult_94_n59;
   wire mult_94_n58;
   wire mult_94_n57;
   wire mult_94_n56;
   wire mult_94_n55;
   wire mult_94_n54;
   wire mult_94_n53;
   wire mult_94_n52;
   wire mult_94_n51;
   wire mult_94_n50;
   wire mult_94_n49;
   wire mult_94_n48;
   wire mult_94_n47;
   wire mult_94_n46;
   wire mult_94_n45;
   wire mult_94_n44;
   wire mult_94_n43;
   wire mult_94_n42;
   wire mult_94_n41;
   wire mult_94_n40;
   wire mult_94_n39;
   wire mult_94_n38;
   wire mult_94_n37;
   wire mult_94_n36;
   wire mult_94_n35;
   wire mult_94_n34;
   wire mult_94_n33;
   wire mult_94_n32;
   wire mult_94_n30;
   wire mult_94_n29;
   wire mult_94_n28;
   wire mult_94_n27;
   wire mult_94_n26;
   wire mult_94_n25;
   wire mult_94_n24;
   wire mult_94_n23;
   wire mult_94_n22;
   wire mult_94_n20;
   wire mult_94_n19;
   wire mult_94_n18;
   wire mult_94_n17;
   wire mult_94_n16;
   wire mult_94_n8;
   wire mult_94_n7;
   wire mult_94_n6;
   wire mult_94_n5;
   wire mult_94_n4;
   wire mult_94_n3;
   wire mult_94_n2;
   wire mult_93_n288;
   wire mult_93_n287;
   wire mult_93_n286;
   wire mult_93_n285;
   wire mult_93_n284;
   wire mult_93_n283;
   wire mult_93_n282;
   wire mult_93_n281;
   wire mult_93_n280;
   wire mult_93_n277;
   wire mult_93_n276;
   wire mult_93_n275;
   wire mult_93_n274;
   wire mult_93_n273;
   wire mult_93_n272;
   wire mult_93_n271;
   wire mult_93_n270;
   wire mult_93_n269;
   wire mult_93_n268;
   wire mult_93_n267;
   wire mult_93_n266;
   wire mult_93_n265;
   wire mult_93_n264;
   wire mult_93_n263;
   wire mult_93_n262;
   wire mult_93_n261;
   wire mult_93_n260;
   wire mult_93_n259;
   wire mult_93_n258;
   wire mult_93_n257;
   wire mult_93_n256;
   wire mult_93_n255;
   wire mult_93_n254;
   wire mult_93_n253;
   wire mult_93_n252;
   wire mult_93_n251;
   wire mult_93_n250;
   wire mult_93_n249;
   wire mult_93_n248;
   wire mult_93_n247;
   wire mult_93_n246;
   wire mult_93_n245;
   wire mult_93_n244;
   wire mult_93_n243;
   wire mult_93_n242;
   wire mult_93_n241;
   wire mult_93_n240;
   wire mult_93_n239;
   wire mult_93_n238;
   wire mult_93_n237;
   wire mult_93_n236;
   wire mult_93_n235;
   wire mult_93_n234;
   wire mult_93_n233;
   wire mult_93_n232;
   wire mult_93_n231;
   wire mult_93_n230;
   wire mult_93_n229;
   wire mult_93_n228;
   wire mult_93_n227;
   wire mult_93_n225;
   wire mult_93_n221;
   wire mult_93_n220;
   wire mult_93_n219;
   wire mult_93_n218;
   wire mult_93_n217;
   wire mult_93_n216;
   wire mult_93_n215;
   wire mult_93_n214;
   wire mult_93_n213;
   wire mult_93_n212;
   wire mult_93_n211;
   wire mult_93_n210;
   wire mult_93_n109;
   wire mult_93_n108;
   wire mult_93_n107;
   wire mult_93_n106;
   wire mult_93_n105;
   wire mult_93_n104;
   wire mult_93_n101;
   wire mult_93_n100;
   wire mult_93_n99;
   wire mult_93_n98;
   wire mult_93_n97;
   wire mult_93_n96;
   wire mult_93_n93;
   wire mult_93_n92;
   wire mult_93_n91;
   wire mult_93_n90;
   wire mult_93_n89;
   wire mult_93_n88;
   wire mult_93_n87;
   wire mult_93_n86;
   wire mult_93_n84;
   wire mult_93_n83;
   wire mult_93_n82;
   wire mult_93_n80;
   wire mult_93_n79;
   wire mult_93_n78;
   wire mult_93_n77;
   wire mult_93_n73;
   wire mult_93_n72;
   wire mult_93_n61;
   wire mult_93_n60;
   wire mult_93_n59;
   wire mult_93_n58;
   wire mult_93_n57;
   wire mult_93_n56;
   wire mult_93_n55;
   wire mult_93_n54;
   wire mult_93_n53;
   wire mult_93_n52;
   wire mult_93_n51;
   wire mult_93_n50;
   wire mult_93_n49;
   wire mult_93_n48;
   wire mult_93_n47;
   wire mult_93_n46;
   wire mult_93_n45;
   wire mult_93_n44;
   wire mult_93_n43;
   wire mult_93_n42;
   wire mult_93_n41;
   wire mult_93_n40;
   wire mult_93_n39;
   wire mult_93_n38;
   wire mult_93_n37;
   wire mult_93_n36;
   wire mult_93_n35;
   wire mult_93_n34;
   wire mult_93_n33;
   wire mult_93_n32;
   wire mult_93_n30;
   wire mult_93_n29;
   wire mult_93_n28;
   wire mult_93_n27;
   wire mult_93_n26;
   wire mult_93_n25;
   wire mult_93_n24;
   wire mult_93_n23;
   wire mult_93_n22;
   wire mult_93_n20;
   wire mult_93_n19;
   wire mult_93_n18;
   wire mult_93_n17;
   wire mult_93_n16;
   wire mult_93_n8;
   wire mult_93_n7;
   wire mult_93_n6;
   wire mult_93_n5;
   wire mult_93_n4;
   wire mult_93_n3;
   wire mult_93_n2;
   wire add_97_n1;
   wire mult_90_n295;
   wire mult_90_n294;
   wire mult_90_n293;
   wire mult_90_n292;
   wire mult_90_n291;
   wire mult_90_n290;
   wire mult_90_n289;
   wire mult_90_n288;
   wire mult_90_n287;
   wire mult_90_n286;
   wire mult_90_n285;
   wire mult_90_n284;
   wire mult_90_n283;
   wire mult_90_n282;
   wire mult_90_n281;
   wire mult_90_n280;
   wire mult_90_n279;
   wire mult_90_n278;
   wire mult_90_n277;
   wire mult_90_n276;
   wire mult_90_n275;
   wire mult_90_n274;
   wire mult_90_n273;
   wire mult_90_n272;
   wire mult_90_n271;
   wire mult_90_n270;
   wire mult_90_n269;
   wire mult_90_n268;
   wire mult_90_n267;
   wire mult_90_n266;
   wire mult_90_n265;
   wire mult_90_n264;
   wire mult_90_n263;
   wire mult_90_n262;
   wire mult_90_n261;
   wire mult_90_n260;
   wire mult_90_n259;
   wire mult_90_n258;
   wire mult_90_n257;
   wire mult_90_n256;
   wire mult_90_n255;
   wire mult_90_n254;
   wire mult_90_n253;
   wire mult_90_n252;
   wire mult_90_n251;
   wire mult_90_n250;
   wire mult_90_n249;
   wire mult_90_n248;
   wire mult_90_n247;
   wire mult_90_n246;
   wire mult_90_n245;
   wire mult_90_n244;
   wire mult_90_n243;
   wire mult_90_n242;
   wire mult_90_n241;
   wire mult_90_n240;
   wire mult_90_n239;
   wire mult_90_n238;
   wire mult_90_n237;
   wire mult_90_n236;
   wire mult_90_n235;
   wire mult_90_n234;
   wire mult_90_n231;
   wire mult_90_n230;
   wire mult_90_n229;
   wire mult_90_n228;
   wire mult_90_n227;
   wire mult_90_n226;
   wire mult_90_n225;
   wire mult_90_n224;
   wire mult_90_n223;
   wire mult_90_n222;
   wire mult_90_n221;
   wire mult_90_n220;
   wire mult_90_n219;
   wire mult_90_n218;
   wire mult_90_n217;
   wire mult_90_n216;
   wire mult_90_n215;
   wire mult_90_n214;
   wire mult_90_n112;
   wire mult_90_n111;
   wire mult_90_n110;
   wire mult_90_n109;
   wire mult_90_n108;
   wire mult_90_n107;
   wire mult_90_n104;
   wire mult_90_n103;
   wire mult_90_n102;
   wire mult_90_n101;
   wire mult_90_n100;
   wire mult_90_n99;
   wire mult_90_n96;
   wire mult_90_n95;
   wire mult_90_n94;
   wire mult_90_n93;
   wire mult_90_n92;
   wire mult_90_n91;
   wire mult_90_n90;
   wire mult_90_n89;
   wire mult_90_n87;
   wire mult_90_n86;
   wire mult_90_n85;
   wire mult_90_n83;
   wire mult_90_n82;
   wire mult_90_n81;
   wire mult_90_n80;
   wire mult_90_n76;
   wire mult_90_n75;
   wire mult_90_n63;
   wire mult_90_n62;
   wire mult_90_n61;
   wire mult_90_n60;
   wire mult_90_n59;
   wire mult_90_n58;
   wire mult_90_n57;
   wire mult_90_n56;
   wire mult_90_n55;
   wire mult_90_n54;
   wire mult_90_n53;
   wire mult_90_n52;
   wire mult_90_n51;
   wire mult_90_n50;
   wire mult_90_n49;
   wire mult_90_n48;
   wire mult_90_n47;
   wire mult_90_n46;
   wire mult_90_n45;
   wire mult_90_n44;
   wire mult_90_n43;
   wire mult_90_n42;
   wire mult_90_n41;
   wire mult_90_n40;
   wire mult_90_n39;
   wire mult_90_n38;
   wire mult_90_n37;
   wire mult_90_n36;
   wire mult_90_n35;
   wire mult_90_n34;
   wire mult_90_n32;
   wire mult_90_n31;
   wire mult_90_n30;
   wire mult_90_n29;
   wire mult_90_n28;
   wire mult_90_n27;
   wire mult_90_n26;
   wire mult_90_n25;
   wire mult_90_n24;
   wire mult_90_n22;
   wire mult_90_n21;
   wire mult_90_n20;
   wire mult_90_n19;
   wire mult_90_n18;
   wire mult_90_n17;
   wire mult_90_n10;
   wire mult_90_n9;
   wire mult_90_n8;
   wire mult_90_n7;
   wire mult_90_n6;
   wire mult_90_n5;
   wire mult_90_n4;
   wire mult_90_n3;
   wire mult_90_n2;
   wire sub_92_n10;
   wire sub_92_n9;
   wire sub_92_n8;
   wire sub_92_n7;
   wire sub_92_n6;
   wire sub_92_n5;
   wire sub_92_n4;
   wire sub_92_n3;
   wire sub_92_n2;
   wire sub_92_n1;
   wire [8:0] tmpfb;
   wire [8:0] w;
   wire [7:0] tmpDin;
   wire [7:0] s1;
   wire [7:2] add_97_carry;
   wire [8:1] sub_92_carry;

   CLKBUF_X2 FE_OFC3_mult_94_n235 (.A(mult_94_n235),
	.Z(FE_OFN3_mult_94_n235));
   CLKBUF_X2 FE_OFC2_mult_93_n235 (.A(mult_93_n235),
	.Z(FE_OFN2_mult_93_n235));
   CLKBUF_X2 FE_OFC1_mult_93_n242 (.A(mult_93_n242),
	.Z(FE_OFN1_mult_93_n242));
   CLKBUF_X2 FE_OFC0_mult_94_n242 (.A(mult_94_n242),
	.Z(FE_OFN0_mult_94_n242));
   AOI21_X1 FE_RC_9_0 (.A(mult_93_n241),
	.B1(FE_OFN2_mult_93_n235),
	.B2(mult_93_n234),
	.ZN(mult_93_n240));
   AOI21_X1 FE_RC_8_0 (.A(mult_93_n265),
	.B1(FE_OFN1_mult_93_n242),
	.B2(mult_93_n244),
	.ZN(mult_93_n264));
   AOI21_X1 FE_RC_7_0 (.A(mult_93_n285),
	.B1(FE_DBTN2_b0_0),
	.B2(mult_93_n258),
	.ZN(mult_93_n286));
   OAI21_X1 FE_RC_6_0 (.A(mult_90_n236),
	.B1(mult_90_n217),
	.B2(mult_90_n214),
	.ZN(mult_90_n235));
   AOI21_X1 FE_RC_5_0 (.A(mult_90_n241),
	.B1(mult_90_n229),
	.B2(mult_90_n238),
	.ZN(mult_90_n240));
   AOI21_X1 FE_RC_4_0 (.A(mult_90_n253),
	.B1(mult_90_n242),
	.B2(mult_90_n244),
	.ZN(mult_90_n252));
   AOI21_X1 FE_RC_3_0 (.A(mult_90_n278),
	.B1(mult_90_n231),
	.B2(mult_90_n272),
	.ZN(mult_90_n279));
   AOI21_X1 FE_RC_2_0 (.A(mult_94_n241),
	.B1(FE_OFN3_mult_94_n235),
	.B2(mult_94_n234),
	.ZN(mult_94_n240));
   AOI21_X1 FE_RC_1_0 (.A(mult_94_n265),
	.B1(FE_OFN0_mult_94_n242),
	.B2(mult_94_n244),
	.ZN(mult_94_n264));
   AOI21_X1 FE_RC_0_0 (.A(mult_94_n285),
	.B1(FE_DBTN2_b0_0),
	.B2(mult_94_n258),
	.ZN(mult_94_n286));
   INV_X1 FE_DBTC5_b0_7 (.A(b0[7]),
	.ZN(FE_DBTN5_b0_7));
   INV_X1 FE_DBTC4_b0_5 (.A(b0[5]),
	.ZN(FE_DBTN4_b0_5));
   INV_X1 FE_DBTC3_b0_3 (.A(b0[3]),
	.ZN(FE_DBTN3_b0_3));
   INV_X1 FE_DBTC2_b0_0 (.A(b0[0]),
	.ZN(FE_DBTN2_b0_0));
   INV_X1 FE_DBTC1_tmpfb_0 (.A(tmpfb[0]),
	.ZN(FE_DBTN1_tmpfb_0));
   INV_X1 FE_DBTC0_tmpfb_1 (.A(tmpfb[1]),
	.ZN(FE_DBTN0_tmpfb_1));
   DFFR_X1 tmprv_out_reg (.D(tmprvin),
	.RN(rst),
	.CK(clk),
	.Q(vout));
   DFFR_X1 tmpfb_reg_8_ (.D(n41),
	.RN(rst),
	.CK(clk),
	.Q(tmpfb[8]));
   DFFR_X1 tmpfb_reg_7_ (.D(n42),
	.RN(rst),
	.CK(clk),
	.Q(tmpfb[7]));
   DFFR_X1 tmpfb_reg_6_ (.D(n43),
	.RN(rst),
	.CK(clk),
	.Q(tmpfb[6]));
   DFFR_X1 tmpfb_reg_5_ (.D(n44),
	.RN(rst),
	.CK(clk),
	.Q(tmpfb[5]));
   DFFR_X1 tmpfb_reg_4_ (.D(n45),
	.RN(rst),
	.CK(clk),
	.Q(tmpfb[4]));
   DFFR_X1 tmpfb_reg_3_ (.D(n46),
	.RN(rst),
	.CK(clk),
	.Q(tmpfb[3]));
   DFFR_X1 tmpfb_reg_2_ (.D(n47),
	.RN(rst),
	.CK(clk),
	.Q(tmpfb[2]));
   DFFR_X1 tmpfb_reg_1_ (.D(n48),
	.RN(rst),
	.CK(clk),
	.Q(tmpfb[1]));
   DFFR_X1 tmpfb_reg_0_ (.D(n49),
	.RN(rst),
	.CK(clk),
	.Q(tmpfb[0]));
   DFFR_X1 tmpDin_reg_7_ (.D(n57),
	.RN(rst),
	.CK(clk),
	.Q(tmpDin[7]));
   DFFR_X1 tmpDin_reg_6_ (.D(n56),
	.RN(rst),
	.CK(clk),
	.Q(tmpDin[6]));
   DFFR_X1 tmpDin_reg_5_ (.D(n55),
	.RN(rst),
	.CK(clk),
	.Q(tmpDin[5]));
   DFFR_X1 tmpDin_reg_4_ (.D(n54),
	.RN(rst),
	.CK(clk),
	.Q(tmpDin[4]));
   DFFR_X1 tmpDin_reg_3_ (.D(n53),
	.RN(rst),
	.CK(clk),
	.Q(tmpDin[3]));
   DFFR_X1 tmpDin_reg_2_ (.D(n52),
	.RN(rst),
	.CK(clk),
	.Q(tmpDin[2]));
   DFFR_X1 tmpDin_reg_1_ (.D(n51),
	.RN(rst),
	.CK(clk),
	.Q(tmpDin[1]));
   DFFR_X1 tmpDin_reg_0_ (.D(n50),
	.RN(rst),
	.CK(clk),
	.Q(tmpDin[0]));
   DFFR_X1 tmpDout_reg_7_ (.D(s1[7]),
	.RN(rst),
	.CK(clk),
	.Q(Dout[7]));
   DFFR_X1 tmpDout_reg_6_ (.D(s1[6]),
	.RN(rst),
	.CK(clk),
	.Q(Dout[6]));
   DFFR_X1 tmpDout_reg_5_ (.D(s1[5]),
	.RN(rst),
	.CK(clk),
	.Q(Dout[5]));
   DFFR_X1 tmpDout_reg_4_ (.D(s1[4]),
	.RN(rst),
	.CK(clk),
	.Q(Dout[4]));
   DFFR_X1 tmpDout_reg_3_ (.D(s1[3]),
	.RN(rst),
	.CK(clk),
	.Q(Dout[3]));
   DFFR_X1 tmpDout_reg_2_ (.D(s1[2]),
	.RN(rst),
	.CK(clk),
	.Q(Dout[2]));
   DFFR_X1 tmpDout_reg_1_ (.D(s1[1]),
	.RN(rst),
	.CK(clk),
	.Q(Dout[1]));
   DFFR_X1 tmpDout_reg_0_ (.D(s1[0]),
	.RN(rst),
	.CK(clk),
	.Q(Dout[0]));
   DFFR_X1 tmprvin_reg (.D(vin),
	.RN(rst),
	.CK(clk),
	.Q(tmprvin),
	.QN(n37));
   INV_X1 U39 (.A(n10),
	.ZN(n49));
   AOI22_X1 U40 (.A1(tmpfb[0]),
	.A2(n37),
	.B1(w[0]),
	.B2(tmprvin),
	.ZN(n10));
   INV_X1 U41 (.A(n19),
	.ZN(n41));
   AOI22_X1 U42 (.A1(tmpfb[8]),
	.A2(n37),
	.B1(w[8]),
	.B2(tmprvin),
	.ZN(n19));
   INV_X1 U43 (.A(n13),
	.ZN(n47));
   AOI22_X1 U44 (.A1(tmpfb[2]),
	.A2(n37),
	.B1(w[2]),
	.B2(tmprvin),
	.ZN(n13));
   INV_X1 U45 (.A(n14),
	.ZN(n46));
   AOI22_X1 U46 (.A1(tmpfb[3]),
	.A2(n37),
	.B1(w[3]),
	.B2(tmprvin),
	.ZN(n14));
   INV_X1 U47 (.A(n15),
	.ZN(n45));
   AOI22_X1 U48 (.A1(tmpfb[4]),
	.A2(n37),
	.B1(w[4]),
	.B2(tmprvin),
	.ZN(n15));
   INV_X1 U49 (.A(n16),
	.ZN(n44));
   AOI22_X1 U50 (.A1(tmpfb[5]),
	.A2(n37),
	.B1(w[5]),
	.B2(tmprvin),
	.ZN(n16));
   INV_X1 U51 (.A(n17),
	.ZN(n43));
   AOI22_X1 U52 (.A1(tmpfb[6]),
	.A2(n37),
	.B1(w[6]),
	.B2(tmprvin),
	.ZN(n17));
   INV_X1 U53 (.A(n18),
	.ZN(n42));
   AOI22_X1 U54 (.A1(tmpfb[7]),
	.A2(n37),
	.B1(w[7]),
	.B2(tmprvin),
	.ZN(n18));
   INV_X1 U55 (.A(n12),
	.ZN(n48));
   AOI22_X1 U56 (.A1(tmpfb[1]),
	.A2(n37),
	.B1(w[1]),
	.B2(tmprvin),
	.ZN(n12));
   INV_X1 U57 (.A(vin),
	.ZN(n58));
   INV_X1 U58 (.A(n1),
	.ZN(n50));
   AOI22_X1 U59 (.A1(vin),
	.A2(Din[0]),
	.B1(tmpDin[0]),
	.B2(n58),
	.ZN(n1));
   INV_X1 U60 (.A(n9),
	.ZN(n57));
   AOI22_X1 U61 (.A1(Din[7]),
	.A2(vin),
	.B1(tmpDin[7]),
	.B2(n58),
	.ZN(n9));
   INV_X1 U62 (.A(n3),
	.ZN(n51));
   AOI22_X1 U63 (.A1(Din[1]),
	.A2(vin),
	.B1(tmpDin[1]),
	.B2(n58),
	.ZN(n3));
   INV_X1 U64 (.A(n4),
	.ZN(n52));
   AOI22_X1 U65 (.A1(Din[2]),
	.A2(vin),
	.B1(tmpDin[2]),
	.B2(n58),
	.ZN(n4));
   INV_X1 U66 (.A(n5),
	.ZN(n53));
   AOI22_X1 U67 (.A1(Din[3]),
	.A2(vin),
	.B1(tmpDin[3]),
	.B2(n58),
	.ZN(n5));
   INV_X1 U68 (.A(n6),
	.ZN(n54));
   AOI22_X1 U69 (.A1(Din[4]),
	.A2(vin),
	.B1(tmpDin[4]),
	.B2(n58),
	.ZN(n6));
   INV_X1 U70 (.A(n7),
	.ZN(n55));
   AOI22_X1 U71 (.A1(Din[5]),
	.A2(vin),
	.B1(tmpDin[5]),
	.B2(n58),
	.ZN(n7));
   INV_X1 U72 (.A(n8),
	.ZN(n56));
   AOI22_X1 U73 (.A1(Din[6]),
	.A2(vin),
	.B1(tmpDin[6]),
	.B2(n58),
	.ZN(n8));
   XOR2_X1 mult_94_U277 (.A(FE_DBTN0_tmpfb_1),
	.B(b0[3]),
	.Z(mult_94_n288));
   XOR2_X1 mult_94_U276 (.A(b0[3]),
	.B(b0[2]),
	.Z(mult_94_n289));
   NAND2_X1 mult_94_U275 (.A1(FE_OFN3_mult_94_n235),
	.A2(mult_94_n289),
	.ZN(mult_94_n234));
   XOR2_X1 mult_94_U274 (.A(tmpfb[2]),
	.B(FE_DBTN3_b0_3),
	.Z(mult_94_n233));
   OAI22_X1 mult_94_U273 (.A1(mult_94_n288),
	.A2(mult_94_n234),
	.B1(FE_OFN3_mult_94_n235),
	.B2(mult_94_n233),
	.ZN(mult_94_n100));
   XOR2_X1 mult_94_U272 (.A(FE_DBTN1_tmpfb_0),
	.B(b0[3]),
	.Z(mult_94_n287));
   OAI22_X1 mult_94_U271 (.A1(mult_94_n287),
	.A2(mult_94_n234),
	.B1(FE_OFN3_mult_94_n235),
	.B2(mult_94_n288),
	.ZN(mult_94_n101));
   XNOR2_X1 mult_94_U270 (.A(tmpfb[8]),
	.B(b0[1]),
	.ZN(mult_94_n285));
   NAND2_X1 mult_94_U269 (.A1(b0[1]),
	.A2(FE_DBTN2_b0_0),
	.ZN(mult_94_n258));
   XNOR2_X1 mult_94_U267 (.A(tmpfb[7]),
	.B(b0[1]),
	.ZN(mult_94_n284));
   OAI22_X1 mult_94_U266 (.A1(mult_94_n284),
	.A2(mult_94_n258),
	.B1(mult_94_n285),
	.B2(FE_DBTN2_b0_0),
	.ZN(mult_94_n104));
   XNOR2_X1 mult_94_U265 (.A(tmpfb[6]),
	.B(b0[1]),
	.ZN(mult_94_n283));
   OAI22_X1 mult_94_U264 (.A1(mult_94_n283),
	.A2(mult_94_n258),
	.B1(mult_94_n284),
	.B2(FE_DBTN2_b0_0),
	.ZN(mult_94_n105));
   XNOR2_X1 mult_94_U263 (.A(tmpfb[5]),
	.B(b0[1]),
	.ZN(mult_94_n282));
   OAI22_X1 mult_94_U262 (.A1(mult_94_n282),
	.A2(mult_94_n258),
	.B1(mult_94_n283),
	.B2(FE_DBTN2_b0_0),
	.ZN(mult_94_n106));
   XNOR2_X1 mult_94_U261 (.A(tmpfb[4]),
	.B(b0[1]),
	.ZN(mult_94_n281));
   OAI22_X1 mult_94_U260 (.A1(mult_94_n281),
	.A2(mult_94_n258),
	.B1(mult_94_n282),
	.B2(FE_DBTN2_b0_0),
	.ZN(mult_94_n107));
   XNOR2_X1 mult_94_U259 (.A(tmpfb[3]),
	.B(b0[1]),
	.ZN(mult_94_n280));
   OAI22_X1 mult_94_U258 (.A1(mult_94_n280),
	.A2(mult_94_n258),
	.B1(mult_94_n281),
	.B2(FE_DBTN2_b0_0),
	.ZN(mult_94_n108));
   XNOR2_X1 mult_94_U257 (.A(tmpfb[2]),
	.B(b0[1]),
	.ZN(mult_94_n259));
   OAI22_X1 mult_94_U256 (.A1(mult_94_n259),
	.A2(mult_94_n258),
	.B1(mult_94_n280),
	.B2(FE_DBTN2_b0_0),
	.ZN(mult_94_n109));
   XOR2_X1 mult_94_U255 (.A(tmpfb[7]),
	.B(FE_DBTN4_b0_5),
	.Z(mult_94_n263));
   XOR2_X1 mult_94_U254 (.A(b0[5]),
	.B(b0[4]),
	.Z(mult_94_n279));
   NAND2_X1 mult_94_U253 (.A1(FE_OFN0_mult_94_n242),
	.A2(mult_94_n279),
	.ZN(mult_94_n244));
   XOR2_X1 mult_94_U252 (.A(tmpfb[8]),
	.B(FE_DBTN4_b0_5),
	.Z(mult_94_n265));
   OAI22_X1 mult_94_U251 (.A1(mult_94_n263),
	.A2(mult_94_n244),
	.B1(FE_OFN0_mult_94_n242),
	.B2(mult_94_n265),
	.ZN(mult_94_n20));
   XOR2_X1 mult_94_U250 (.A(tmpfb[7]),
	.B(FE_DBTN3_b0_3),
	.Z(mult_94_n277));
   XOR2_X1 mult_94_U249 (.A(tmpfb[8]),
	.B(FE_DBTN3_b0_3),
	.Z(mult_94_n241));
   OAI22_X1 mult_94_U248 (.A1(mult_94_n277),
	.A2(mult_94_n234),
	.B1(FE_OFN3_mult_94_n235),
	.B2(mult_94_n241),
	.ZN(mult_94_n30));
   XOR2_X1 mult_94_U247 (.A(tmpfb[2]),
	.B(FE_DBTN5_b0_7),
	.Z(mult_94_n268));
   XOR2_X1 mult_94_U246 (.A(b0[7]),
	.B(b0[6]),
	.Z(mult_94_n278));
   NAND2_X1 mult_94_U245 (.A1(mult_94_n230),
	.A2(mult_94_n278),
	.ZN(mult_94_n231));
   XOR2_X1 mult_94_U244 (.A(tmpfb[3]),
	.B(FE_DBTN5_b0_7),
	.Z(mult_94_n269));
   OAI22_X1 mult_94_U243 (.A1(mult_94_n268),
	.A2(mult_94_n231),
	.B1(mult_94_n230),
	.B2(mult_94_n269),
	.ZN(mult_94_n275));
   XOR2_X1 mult_94_U242 (.A(tmpfb[6]),
	.B(FE_DBTN3_b0_3),
	.Z(mult_94_n239));
   OAI22_X1 mult_94_U241 (.A1(mult_94_n239),
	.A2(mult_94_n234),
	.B1(FE_OFN3_mult_94_n235),
	.B2(mult_94_n277),
	.ZN(mult_94_n276));
   OR2_X1 mult_94_U240 (.A1(mult_94_n275),
	.A2(mult_94_n276),
	.ZN(mult_94_n36));
   XNOR2_X1 mult_94_U239 (.A(mult_94_n275),
	.B(mult_94_n276),
	.ZN(mult_94_n37));
   OR3_X1 mult_94_U238 (.A1(mult_94_n230),
	.A2(tmpfb[0]),
	.A3(FE_DBTN5_b0_7),
	.ZN(mult_94_n274));
   OAI21_X1 mult_94_U237 (.A(mult_94_n274),
	.B1(FE_DBTN5_b0_7),
	.B2(mult_94_n231),
	.ZN(mult_94_n72));
   OR3_X1 mult_94_U236 (.A1(FE_OFN0_mult_94_n242),
	.A2(tmpfb[0]),
	.A3(FE_DBTN4_b0_5),
	.ZN(mult_94_n273));
   OAI21_X1 mult_94_U235 (.A(mult_94_n273),
	.B1(FE_DBTN4_b0_5),
	.B2(mult_94_n244),
	.ZN(mult_94_n73));
   XOR2_X1 mult_94_U234 (.A(tmpfb[6]),
	.B(FE_DBTN5_b0_7),
	.Z(mult_94_n272));
   XNOR2_X1 mult_94_U233 (.A(tmpfb[7]),
	.B(b0[7]),
	.ZN(mult_94_n232));
   OAI22_X1 mult_94_U232 (.A1(mult_94_n272),
	.A2(mult_94_n231),
	.B1(mult_94_n230),
	.B2(mult_94_n232),
	.ZN(mult_94_n77));
   XOR2_X1 mult_94_U231 (.A(tmpfb[5]),
	.B(FE_DBTN5_b0_7),
	.Z(mult_94_n271));
   OAI22_X1 mult_94_U230 (.A1(mult_94_n271),
	.A2(mult_94_n231),
	.B1(mult_94_n230),
	.B2(mult_94_n272),
	.ZN(mult_94_n78));
   XOR2_X1 mult_94_U229 (.A(tmpfb[4]),
	.B(FE_DBTN5_b0_7),
	.Z(mult_94_n270));
   OAI22_X1 mult_94_U228 (.A1(mult_94_n270),
	.A2(mult_94_n231),
	.B1(mult_94_n230),
	.B2(mult_94_n271),
	.ZN(mult_94_n79));
   OAI22_X1 mult_94_U227 (.A1(mult_94_n269),
	.A2(mult_94_n231),
	.B1(mult_94_n230),
	.B2(mult_94_n270),
	.ZN(mult_94_n80));
   XOR2_X1 mult_94_U226 (.A(FE_DBTN0_tmpfb_1),
	.B(b0[7]),
	.Z(mult_94_n267));
   OAI22_X1 mult_94_U225 (.A1(mult_94_n267),
	.A2(mult_94_n231),
	.B1(mult_94_n230),
	.B2(mult_94_n268),
	.ZN(mult_94_n82));
   XOR2_X1 mult_94_U224 (.A(FE_DBTN1_tmpfb_0),
	.B(b0[7]),
	.Z(mult_94_n266));
   OAI22_X1 mult_94_U223 (.A1(mult_94_n266),
	.A2(mult_94_n231),
	.B1(mult_94_n230),
	.B2(mult_94_n267),
	.ZN(mult_94_n83));
   NOR2_X1 mult_94_U222 (.A1(mult_94_n230),
	.A2(FE_DBTN1_tmpfb_0),
	.ZN(mult_94_n84));
   XOR2_X1 mult_94_U220 (.A(tmpfb[6]),
	.B(FE_DBTN4_b0_5),
	.Z(mult_94_n262));
   OAI22_X1 mult_94_U219 (.A1(mult_94_n262),
	.A2(mult_94_n244),
	.B1(FE_OFN0_mult_94_n242),
	.B2(mult_94_n263),
	.ZN(mult_94_n86));
   XOR2_X1 mult_94_U218 (.A(tmpfb[5]),
	.B(FE_DBTN4_b0_5),
	.Z(mult_94_n261));
   OAI22_X1 mult_94_U217 (.A1(mult_94_n261),
	.A2(mult_94_n244),
	.B1(FE_OFN0_mult_94_n242),
	.B2(mult_94_n262),
	.ZN(mult_94_n87));
   XOR2_X1 mult_94_U216 (.A(tmpfb[4]),
	.B(FE_DBTN4_b0_5),
	.Z(mult_94_n260));
   OAI22_X1 mult_94_U215 (.A1(mult_94_n260),
	.A2(mult_94_n244),
	.B1(FE_OFN0_mult_94_n242),
	.B2(mult_94_n261),
	.ZN(mult_94_n88));
   XOR2_X1 mult_94_U214 (.A(tmpfb[3]),
	.B(FE_DBTN4_b0_5),
	.Z(mult_94_n247));
   OAI22_X1 mult_94_U213 (.A1(mult_94_n247),
	.A2(mult_94_n244),
	.B1(FE_OFN0_mult_94_n242),
	.B2(mult_94_n260),
	.ZN(mult_94_n89));
   OAI22_X1 mult_94_U212 (.A1(tmpfb[1]),
	.A2(mult_94_n258),
	.B1(mult_94_n259),
	.B2(FE_DBTN2_b0_0),
	.ZN(mult_94_n257));
   NAND3_X1 mult_94_U211 (.A1(mult_94_n257),
	.A2(FE_DBTN0_tmpfb_1),
	.A3(b0[1]),
	.ZN(mult_94_n255));
   NAND2_X1 mult_94_U210 (.A1(mult_94_n222),
	.A2(mult_94_n257),
	.ZN(mult_94_n256));
   MUX2_X1 mult_94_U209 (.A(mult_94_n255),
	.B(mult_94_n256),
	.S(tmpfb[0]),
	.Z(mult_94_n254));
   NAND3_X1 mult_94_U208 (.A1(mult_94_n222),
	.A2(FE_DBTN1_tmpfb_0),
	.A3(b0[3]),
	.ZN(mult_94_n253));
   OAI21_X1 mult_94_U207 (.A(mult_94_n253),
	.B1(FE_DBTN3_b0_3),
	.B2(mult_94_n234),
	.ZN(mult_94_n252));
   AOI222_X1 mult_94_U206 (.A1(mult_94_n221),
	.A2(mult_94_n61),
	.B1(mult_94_n252),
	.B2(mult_94_n221),
	.C1(mult_94_n252),
	.C2(mult_94_n61),
	.ZN(mult_94_n251));
   AOI222_X1 mult_94_U205 (.A1(mult_94_n217),
	.A2(mult_94_n59),
	.B1(mult_94_n217),
	.B2(mult_94_n60),
	.C1(mult_94_n60),
	.C2(mult_94_n59),
	.ZN(mult_94_n250));
   AOI222_X1 mult_94_U204 (.A1(mult_94_n216),
	.A2(mult_94_n55),
	.B1(mult_94_n216),
	.B2(mult_94_n58),
	.C1(mult_94_n58),
	.C2(mult_94_n55),
	.ZN(mult_94_n249));
   AOI222_X1 mult_94_U203 (.A1(mult_94_n212),
	.A2(mult_94_n51),
	.B1(mult_94_n212),
	.B2(mult_94_n54),
	.C1(mult_94_n54),
	.C2(mult_94_n51),
	.ZN(mult_94_n248));
   XOR2_X1 mult_94_U202 (.A(tmpfb[2]),
	.B(FE_DBTN4_b0_5),
	.Z(mult_94_n246));
   OAI22_X1 mult_94_U201 (.A1(mult_94_n246),
	.A2(mult_94_n244),
	.B1(FE_OFN0_mult_94_n242),
	.B2(mult_94_n247),
	.ZN(mult_94_n90));
   XOR2_X1 mult_94_U200 (.A(FE_DBTN0_tmpfb_1),
	.B(b0[5]),
	.Z(mult_94_n245));
   OAI22_X1 mult_94_U199 (.A1(mult_94_n245),
	.A2(mult_94_n244),
	.B1(FE_OFN0_mult_94_n242),
	.B2(mult_94_n246),
	.ZN(mult_94_n91));
   XOR2_X1 mult_94_U198 (.A(FE_DBTN1_tmpfb_0),
	.B(b0[5]),
	.Z(mult_94_n243));
   OAI22_X1 mult_94_U197 (.A1(mult_94_n243),
	.A2(mult_94_n244),
	.B1(FE_OFN0_mult_94_n242),
	.B2(mult_94_n245),
	.ZN(mult_94_n92));
   NOR2_X1 mult_94_U196 (.A1(FE_OFN0_mult_94_n242),
	.A2(FE_DBTN1_tmpfb_0),
	.ZN(mult_94_n93));
   XOR2_X1 mult_94_U194 (.A(tmpfb[5]),
	.B(FE_DBTN3_b0_3),
	.Z(mult_94_n238));
   OAI22_X1 mult_94_U193 (.A1(mult_94_n238),
	.A2(mult_94_n234),
	.B1(FE_OFN3_mult_94_n235),
	.B2(mult_94_n239),
	.ZN(mult_94_n96));
   XOR2_X1 mult_94_U192 (.A(tmpfb[4]),
	.B(FE_DBTN3_b0_3),
	.Z(mult_94_n237));
   OAI22_X1 mult_94_U191 (.A1(mult_94_n237),
	.A2(mult_94_n234),
	.B1(FE_OFN3_mult_94_n235),
	.B2(mult_94_n238),
	.ZN(mult_94_n97));
   XOR2_X1 mult_94_U190 (.A(tmpfb[3]),
	.B(FE_DBTN3_b0_3),
	.Z(mult_94_n236));
   OAI22_X1 mult_94_U189 (.A1(mult_94_n236),
	.A2(mult_94_n234),
	.B1(FE_OFN3_mult_94_n235),
	.B2(mult_94_n237),
	.ZN(mult_94_n98));
   OAI22_X1 mult_94_U188 (.A1(mult_94_n233),
	.A2(mult_94_n234),
	.B1(FE_OFN3_mult_94_n235),
	.B2(mult_94_n236),
	.ZN(mult_94_n99));
   XOR2_X1 mult_94_U187 (.A(FE_DBTN5_b0_7),
	.B(tmpfb[8]),
	.Z(mult_94_n229));
   OAI22_X1 mult_94_U186 (.A1(mult_94_n229),
	.A2(mult_94_n230),
	.B1(mult_94_n231),
	.B2(mult_94_n232),
	.ZN(mult_94_n227));
   XOR2_X1 mult_94_U185 (.A(mult_94_n2),
	.B(mult_94_n16),
	.Z(mult_94_n228));
   XNOR2_X1 mult_94_U184 (.A(mult_94_n227),
	.B(mult_94_n228),
	.ZN(m2_tmp_14_));
   XNOR2_X1 mult_94_U177 (.A(b0[6]),
	.B(b0[5]),
	.ZN(mult_94_n230));
   XNOR2_X1 mult_94_U176 (.A(b0[2]),
	.B(b0[1]),
	.ZN(mult_94_n235));
   XNOR2_X1 mult_94_U175 (.A(b0[4]),
	.B(b0[3]),
	.ZN(mult_94_n242));
   INV_X1 mult_94_U174 (.A(mult_94_n264),
	.ZN(mult_94_n214));
   INV_X1 mult_94_U173 (.A(mult_94_n250),
	.ZN(mult_94_n216));
   INV_X1 mult_94_U172 (.A(mult_94_n249),
	.ZN(mult_94_n212));
   INV_X1 mult_94_U171 (.A(FE_OFN3_mult_94_n235),
	.ZN(mult_94_n222));
   INV_X1 mult_94_U170 (.A(mult_94_n248),
	.ZN(mult_94_n211));
   INV_X1 mult_94_U169 (.A(mult_94_n30),
	.ZN(mult_94_n218));
   INV_X1 mult_94_U168 (.A(mult_94_n240),
	.ZN(mult_94_n219));
   INV_X1 mult_94_U167 (.A(mult_94_n286),
	.ZN(mult_94_n223));
   INV_X1 mult_94_U166 (.A(mult_94_n20),
	.ZN(mult_94_n213));
   INV_X1 mult_94_U165 (.A(mult_94_n254),
	.ZN(mult_94_n221));
   INV_X1 mult_94_U164 (.A(mult_94_n251),
	.ZN(mult_94_n217));
   HA_X1 mult_94_U40 (.A(mult_94_n101),
	.B(mult_94_n109),
	.CO(mult_94_n60),
	.S(mult_94_n61));
   FA_X1 mult_94_U39 (.A(mult_94_n108),
	.B(mult_94_n93),
	.CI(mult_94_n100),
	.CO(mult_94_n58),
	.S(mult_94_n59));
   HA_X1 mult_94_U38 (.A(mult_94_n73),
	.B(mult_94_n92),
	.CO(mult_94_n56),
	.S(mult_94_n57));
   FA_X1 mult_94_U37 (.A(mult_94_n99),
	.B(mult_94_n107),
	.CI(mult_94_n57),
	.CO(mult_94_n54),
	.S(mult_94_n55));
   FA_X1 mult_94_U36 (.A(mult_94_n106),
	.B(mult_94_n84),
	.CI(mult_94_n98),
	.CO(mult_94_n52),
	.S(mult_94_n53));
   FA_X1 mult_94_U35 (.A(mult_94_n56),
	.B(mult_94_n91),
	.CI(mult_94_n53),
	.CO(mult_94_n50),
	.S(mult_94_n51));
   HA_X1 mult_94_U34 (.A(mult_94_n72),
	.B(mult_94_n83),
	.CO(mult_94_n48),
	.S(mult_94_n49));
   FA_X1 mult_94_U33 (.A(mult_94_n90),
	.B(mult_94_n105),
	.CI(mult_94_n97),
	.CO(mult_94_n46),
	.S(mult_94_n47));
   FA_X1 mult_94_U32 (.A(mult_94_n52),
	.B(mult_94_n49),
	.CI(mult_94_n47),
	.CO(mult_94_n44),
	.S(mult_94_n45));
   HA_X1 mult_94_U31 (.A(mult_94_n82),
	.B(mult_94_n89),
	.CO(mult_94_n42),
	.S(mult_94_n43));
   FA_X1 mult_94_U30 (.A(mult_94_n96),
	.B(mult_94_n104),
	.CI(mult_94_n48),
	.CO(mult_94_n40),
	.S(mult_94_n41));
   FA_X1 mult_94_U29 (.A(mult_94_n46),
	.B(mult_94_n43),
	.CI(mult_94_n41),
	.CO(mult_94_n38),
	.S(mult_94_n39));
   FA_X1 mult_94_U26 (.A(mult_94_n223),
	.B(mult_94_n88),
	.CI(mult_94_n42),
	.CO(mult_94_n34),
	.S(mult_94_n35));
   FA_X1 mult_94_U25 (.A(mult_94_n40),
	.B(mult_94_n37),
	.CI(mult_94_n35),
	.CO(mult_94_n32),
	.S(mult_94_n33));
   FA_X1 mult_94_U23 (.A(mult_94_n80),
	.B(mult_94_n87),
	.CI(mult_94_n218),
	.CO(mult_94_n28),
	.S(mult_94_n29));
   FA_X1 mult_94_U22 (.A(mult_94_n34),
	.B(mult_94_n36),
	.CI(mult_94_n29),
	.CO(mult_94_n26),
	.S(mult_94_n27));
   FA_X1 mult_94_U21 (.A(mult_94_n86),
	.B(mult_94_n30),
	.CI(mult_94_n219),
	.CO(mult_94_n24),
	.S(mult_94_n25));
   FA_X1 mult_94_U20 (.A(mult_94_n28),
	.B(mult_94_n79),
	.CI(mult_94_n25),
	.CO(mult_94_n22),
	.S(mult_94_n23));
   FA_X1 mult_94_U18 (.A(mult_94_n213),
	.B(mult_94_n78),
	.CI(mult_94_n24),
	.CO(mult_94_n18),
	.S(mult_94_n19));
   FA_X1 mult_94_U17 (.A(mult_94_n77),
	.B(mult_94_n20),
	.CI(mult_94_n214),
	.CO(mult_94_n16),
	.S(mult_94_n17));
   FA_X1 mult_94_U9 (.A(mult_94_n45),
	.B(mult_94_n50),
	.CI(mult_94_n211),
	.CO(mult_94_n8),
	.S(m2_tmp_7_));
   FA_X1 mult_94_U8 (.A(mult_94_n39),
	.B(mult_94_n44),
	.CI(mult_94_n8),
	.CO(mult_94_n7),
	.S(m2_tmp_8_));
   FA_X1 mult_94_U7 (.A(mult_94_n33),
	.B(mult_94_n38),
	.CI(mult_94_n7),
	.CO(mult_94_n6),
	.S(m2_tmp_9_));
   FA_X1 mult_94_U6 (.A(mult_94_n27),
	.B(mult_94_n32),
	.CI(mult_94_n6),
	.CO(mult_94_n5),
	.S(m2_tmp_10_));
   FA_X1 mult_94_U5 (.A(mult_94_n23),
	.B(mult_94_n26),
	.CI(mult_94_n5),
	.CO(mult_94_n4),
	.S(m2_tmp_11_));
   FA_X1 mult_94_U4 (.A(mult_94_n19),
	.B(mult_94_n22),
	.CI(mult_94_n4),
	.CO(mult_94_n3),
	.S(m2_tmp_12_));
   FA_X1 mult_94_U3 (.A(mult_94_n18),
	.B(mult_94_n17),
	.CI(mult_94_n3),
	.CO(mult_94_n2),
	.S(m2_tmp_13_));
   XOR2_X1 mult_93_U277 (.A(mult_93_n220),
	.B(b0[3]),
	.Z(mult_93_n288));
   NAND2_X1 mult_93_U275 (.A1(FE_OFN2_mult_93_n235),
	.A2(mult_94_n289),
	.ZN(mult_93_n234));
   XOR2_X1 mult_93_U274 (.A(w[2]),
	.B(FE_DBTN3_b0_3),
	.Z(mult_93_n233));
   OAI22_X1 mult_93_U273 (.A1(mult_93_n288),
	.A2(mult_93_n234),
	.B1(FE_OFN2_mult_93_n235),
	.B2(mult_93_n233),
	.ZN(mult_93_n100));
   XOR2_X1 mult_93_U272 (.A(mult_93_n221),
	.B(b0[3]),
	.Z(mult_93_n287));
   OAI22_X1 mult_93_U271 (.A1(mult_93_n287),
	.A2(mult_93_n234),
	.B1(FE_OFN2_mult_93_n235),
	.B2(mult_93_n288),
	.ZN(mult_93_n101));
   XNOR2_X1 mult_93_U270 (.A(w[8]),
	.B(b0[1]),
	.ZN(mult_93_n285));
   NAND2_X1 mult_93_U269 (.A1(b0[1]),
	.A2(FE_DBTN2_b0_0),
	.ZN(mult_93_n258));
   XNOR2_X1 mult_93_U267 (.A(w[7]),
	.B(b0[1]),
	.ZN(mult_93_n284));
   OAI22_X1 mult_93_U266 (.A1(mult_93_n284),
	.A2(mult_93_n258),
	.B1(mult_93_n285),
	.B2(FE_DBTN2_b0_0),
	.ZN(mult_93_n104));
   XNOR2_X1 mult_93_U265 (.A(w[6]),
	.B(b0[1]),
	.ZN(mult_93_n283));
   OAI22_X1 mult_93_U264 (.A1(mult_93_n283),
	.A2(mult_93_n258),
	.B1(mult_93_n284),
	.B2(FE_DBTN2_b0_0),
	.ZN(mult_93_n105));
   XNOR2_X1 mult_93_U263 (.A(w[5]),
	.B(b0[1]),
	.ZN(mult_93_n282));
   OAI22_X1 mult_93_U262 (.A1(mult_93_n282),
	.A2(mult_93_n258),
	.B1(mult_93_n283),
	.B2(FE_DBTN2_b0_0),
	.ZN(mult_93_n106));
   XNOR2_X1 mult_93_U261 (.A(w[4]),
	.B(b0[1]),
	.ZN(mult_93_n281));
   OAI22_X1 mult_93_U260 (.A1(mult_93_n281),
	.A2(mult_93_n258),
	.B1(mult_93_n282),
	.B2(FE_DBTN2_b0_0),
	.ZN(mult_93_n107));
   XNOR2_X1 mult_93_U259 (.A(w[3]),
	.B(b0[1]),
	.ZN(mult_93_n280));
   OAI22_X1 mult_93_U258 (.A1(mult_93_n280),
	.A2(mult_93_n258),
	.B1(mult_93_n281),
	.B2(FE_DBTN2_b0_0),
	.ZN(mult_93_n108));
   XNOR2_X1 mult_93_U257 (.A(w[2]),
	.B(b0[1]),
	.ZN(mult_93_n259));
   OAI22_X1 mult_93_U256 (.A1(mult_93_n259),
	.A2(mult_93_n258),
	.B1(mult_93_n280),
	.B2(FE_DBTN2_b0_0),
	.ZN(mult_93_n109));
   XOR2_X1 mult_93_U255 (.A(w[7]),
	.B(FE_DBTN4_b0_5),
	.Z(mult_93_n263));
   NAND2_X1 mult_93_U253 (.A1(FE_OFN1_mult_93_n242),
	.A2(mult_94_n279),
	.ZN(mult_93_n244));
   XOR2_X1 mult_93_U252 (.A(w[8]),
	.B(FE_DBTN4_b0_5),
	.Z(mult_93_n265));
   OAI22_X1 mult_93_U251 (.A1(mult_93_n263),
	.A2(mult_93_n244),
	.B1(FE_OFN1_mult_93_n242),
	.B2(mult_93_n265),
	.ZN(mult_93_n20));
   XOR2_X1 mult_93_U250 (.A(w[7]),
	.B(FE_DBTN3_b0_3),
	.Z(mult_93_n277));
   XOR2_X1 mult_93_U249 (.A(w[8]),
	.B(FE_DBTN3_b0_3),
	.Z(mult_93_n241));
   OAI22_X1 mult_93_U248 (.A1(mult_93_n277),
	.A2(mult_93_n234),
	.B1(FE_OFN2_mult_93_n235),
	.B2(mult_93_n241),
	.ZN(mult_93_n30));
   XOR2_X1 mult_93_U247 (.A(w[2]),
	.B(FE_DBTN5_b0_7),
	.Z(mult_93_n268));
   NAND2_X1 mult_93_U245 (.A1(mult_93_n230),
	.A2(mult_94_n278),
	.ZN(mult_93_n231));
   XOR2_X1 mult_93_U244 (.A(w[3]),
	.B(FE_DBTN5_b0_7),
	.Z(mult_93_n269));
   OAI22_X1 mult_93_U243 (.A1(mult_93_n268),
	.A2(mult_93_n231),
	.B1(mult_93_n230),
	.B2(mult_93_n269),
	.ZN(mult_93_n275));
   XOR2_X1 mult_93_U242 (.A(w[6]),
	.B(FE_DBTN3_b0_3),
	.Z(mult_93_n239));
   OAI22_X1 mult_93_U241 (.A1(mult_93_n239),
	.A2(mult_93_n234),
	.B1(FE_OFN2_mult_93_n235),
	.B2(mult_93_n277),
	.ZN(mult_93_n276));
   OR2_X1 mult_93_U240 (.A1(mult_93_n275),
	.A2(mult_93_n276),
	.ZN(mult_93_n36));
   XNOR2_X1 mult_93_U239 (.A(mult_93_n275),
	.B(mult_93_n276),
	.ZN(mult_93_n37));
   OR3_X1 mult_93_U238 (.A1(mult_93_n230),
	.A2(w[0]),
	.A3(FE_DBTN5_b0_7),
	.ZN(mult_93_n274));
   OAI21_X1 mult_93_U237 (.A(mult_93_n274),
	.B1(FE_DBTN5_b0_7),
	.B2(mult_93_n231),
	.ZN(mult_93_n72));
   OR3_X1 mult_93_U236 (.A1(FE_OFN1_mult_93_n242),
	.A2(w[0]),
	.A3(FE_DBTN4_b0_5),
	.ZN(mult_93_n273));
   OAI21_X1 mult_93_U235 (.A(mult_93_n273),
	.B1(FE_DBTN4_b0_5),
	.B2(mult_93_n244),
	.ZN(mult_93_n73));
   XOR2_X1 mult_93_U234 (.A(w[6]),
	.B(FE_DBTN5_b0_7),
	.Z(mult_93_n272));
   XNOR2_X1 mult_93_U233 (.A(w[7]),
	.B(b0[7]),
	.ZN(mult_93_n232));
   OAI22_X1 mult_93_U232 (.A1(mult_93_n272),
	.A2(mult_93_n231),
	.B1(mult_93_n230),
	.B2(mult_93_n232),
	.ZN(mult_93_n77));
   XOR2_X1 mult_93_U231 (.A(w[5]),
	.B(FE_DBTN5_b0_7),
	.Z(mult_93_n271));
   OAI22_X1 mult_93_U230 (.A1(mult_93_n271),
	.A2(mult_93_n231),
	.B1(mult_93_n230),
	.B2(mult_93_n272),
	.ZN(mult_93_n78));
   XOR2_X1 mult_93_U229 (.A(w[4]),
	.B(FE_DBTN5_b0_7),
	.Z(mult_93_n270));
   OAI22_X1 mult_93_U228 (.A1(mult_93_n270),
	.A2(mult_93_n231),
	.B1(mult_93_n230),
	.B2(mult_93_n271),
	.ZN(mult_93_n79));
   OAI22_X1 mult_93_U227 (.A1(mult_93_n269),
	.A2(mult_93_n231),
	.B1(mult_93_n230),
	.B2(mult_93_n270),
	.ZN(mult_93_n80));
   XOR2_X1 mult_93_U226 (.A(mult_93_n220),
	.B(b0[7]),
	.Z(mult_93_n267));
   OAI22_X1 mult_93_U225 (.A1(mult_93_n267),
	.A2(mult_93_n231),
	.B1(mult_93_n230),
	.B2(mult_93_n268),
	.ZN(mult_93_n82));
   XOR2_X1 mult_93_U224 (.A(mult_93_n221),
	.B(b0[7]),
	.Z(mult_93_n266));
   OAI22_X1 mult_93_U223 (.A1(mult_93_n266),
	.A2(mult_93_n231),
	.B1(mult_93_n230),
	.B2(mult_93_n267),
	.ZN(mult_93_n83));
   NOR2_X1 mult_93_U222 (.A1(mult_93_n230),
	.A2(mult_93_n221),
	.ZN(mult_93_n84));
   XOR2_X1 mult_93_U220 (.A(w[6]),
	.B(FE_DBTN4_b0_5),
	.Z(mult_93_n262));
   OAI22_X1 mult_93_U219 (.A1(mult_93_n262),
	.A2(mult_93_n244),
	.B1(FE_OFN1_mult_93_n242),
	.B2(mult_93_n263),
	.ZN(mult_93_n86));
   XOR2_X1 mult_93_U218 (.A(w[5]),
	.B(FE_DBTN4_b0_5),
	.Z(mult_93_n261));
   OAI22_X1 mult_93_U217 (.A1(mult_93_n261),
	.A2(mult_93_n244),
	.B1(FE_OFN1_mult_93_n242),
	.B2(mult_93_n262),
	.ZN(mult_93_n87));
   XOR2_X1 mult_93_U216 (.A(w[4]),
	.B(FE_DBTN4_b0_5),
	.Z(mult_93_n260));
   OAI22_X1 mult_93_U215 (.A1(mult_93_n260),
	.A2(mult_93_n244),
	.B1(FE_OFN1_mult_93_n242),
	.B2(mult_93_n261),
	.ZN(mult_93_n88));
   XOR2_X1 mult_93_U214 (.A(w[3]),
	.B(FE_DBTN4_b0_5),
	.Z(mult_93_n247));
   OAI22_X1 mult_93_U213 (.A1(mult_93_n247),
	.A2(mult_93_n244),
	.B1(FE_OFN1_mult_93_n242),
	.B2(mult_93_n260),
	.ZN(mult_93_n89));
   OAI22_X1 mult_93_U212 (.A1(w[1]),
	.A2(mult_93_n258),
	.B1(mult_93_n259),
	.B2(FE_DBTN2_b0_0),
	.ZN(mult_93_n257));
   NAND3_X1 mult_93_U211 (.A1(mult_93_n257),
	.A2(mult_93_n220),
	.A3(b0[1]),
	.ZN(mult_93_n255));
   NAND2_X1 mult_93_U210 (.A1(mult_93_n225),
	.A2(mult_93_n257),
	.ZN(mult_93_n256));
   MUX2_X1 mult_93_U209 (.A(mult_93_n255),
	.B(mult_93_n256),
	.S(w[0]),
	.Z(mult_93_n254));
   NAND3_X1 mult_93_U208 (.A1(mult_93_n225),
	.A2(mult_93_n221),
	.A3(b0[3]),
	.ZN(mult_93_n253));
   OAI21_X1 mult_93_U207 (.A(mult_93_n253),
	.B1(FE_DBTN3_b0_3),
	.B2(mult_93_n234),
	.ZN(mult_93_n252));
   AOI222_X1 mult_93_U206 (.A1(mult_93_n219),
	.A2(mult_93_n61),
	.B1(mult_93_n252),
	.B2(mult_93_n219),
	.C1(mult_93_n252),
	.C2(mult_93_n61),
	.ZN(mult_93_n251));
   AOI222_X1 mult_93_U205 (.A1(mult_93_n218),
	.A2(mult_93_n59),
	.B1(mult_93_n218),
	.B2(mult_93_n60),
	.C1(mult_93_n60),
	.C2(mult_93_n59),
	.ZN(mult_93_n250));
   AOI222_X1 mult_93_U204 (.A1(mult_93_n217),
	.A2(mult_93_n55),
	.B1(mult_93_n217),
	.B2(mult_93_n58),
	.C1(mult_93_n58),
	.C2(mult_93_n55),
	.ZN(mult_93_n249));
   AOI222_X1 mult_93_U203 (.A1(mult_93_n216),
	.A2(mult_93_n51),
	.B1(mult_93_n216),
	.B2(mult_93_n54),
	.C1(mult_93_n54),
	.C2(mult_93_n51),
	.ZN(mult_93_n248));
   XOR2_X1 mult_93_U202 (.A(w[2]),
	.B(FE_DBTN4_b0_5),
	.Z(mult_93_n246));
   OAI22_X1 mult_93_U201 (.A1(mult_93_n246),
	.A2(mult_93_n244),
	.B1(FE_OFN1_mult_93_n242),
	.B2(mult_93_n247),
	.ZN(mult_93_n90));
   XOR2_X1 mult_93_U200 (.A(mult_93_n220),
	.B(b0[5]),
	.Z(mult_93_n245));
   OAI22_X1 mult_93_U199 (.A1(mult_93_n245),
	.A2(mult_93_n244),
	.B1(FE_OFN1_mult_93_n242),
	.B2(mult_93_n246),
	.ZN(mult_93_n91));
   XOR2_X1 mult_93_U198 (.A(mult_93_n221),
	.B(b0[5]),
	.Z(mult_93_n243));
   OAI22_X1 mult_93_U197 (.A1(mult_93_n243),
	.A2(mult_93_n244),
	.B1(FE_OFN1_mult_93_n242),
	.B2(mult_93_n245),
	.ZN(mult_93_n92));
   NOR2_X1 mult_93_U196 (.A1(FE_OFN1_mult_93_n242),
	.A2(mult_93_n221),
	.ZN(mult_93_n93));
   XOR2_X1 mult_93_U194 (.A(w[5]),
	.B(FE_DBTN3_b0_3),
	.Z(mult_93_n238));
   OAI22_X1 mult_93_U193 (.A1(mult_93_n238),
	.A2(mult_93_n234),
	.B1(FE_OFN2_mult_93_n235),
	.B2(mult_93_n239),
	.ZN(mult_93_n96));
   XOR2_X1 mult_93_U192 (.A(w[4]),
	.B(FE_DBTN3_b0_3),
	.Z(mult_93_n237));
   OAI22_X1 mult_93_U191 (.A1(mult_93_n237),
	.A2(mult_93_n234),
	.B1(FE_OFN2_mult_93_n235),
	.B2(mult_93_n238),
	.ZN(mult_93_n97));
   XOR2_X1 mult_93_U190 (.A(w[3]),
	.B(FE_DBTN3_b0_3),
	.Z(mult_93_n236));
   OAI22_X1 mult_93_U189 (.A1(mult_93_n236),
	.A2(mult_93_n234),
	.B1(FE_OFN2_mult_93_n235),
	.B2(mult_93_n237),
	.ZN(mult_93_n98));
   OAI22_X1 mult_93_U188 (.A1(mult_93_n233),
	.A2(mult_93_n234),
	.B1(FE_OFN2_mult_93_n235),
	.B2(mult_93_n236),
	.ZN(mult_93_n99));
   XOR2_X1 mult_93_U187 (.A(FE_DBTN5_b0_7),
	.B(w[8]),
	.Z(mult_93_n229));
   OAI22_X1 mult_93_U186 (.A1(mult_93_n229),
	.A2(mult_93_n230),
	.B1(mult_93_n231),
	.B2(mult_93_n232),
	.ZN(mult_93_n227));
   XOR2_X1 mult_93_U185 (.A(mult_93_n2),
	.B(mult_93_n16),
	.Z(mult_93_n228));
   XNOR2_X1 mult_93_U184 (.A(mult_93_n227),
	.B(mult_93_n228),
	.ZN(ff_tmp_14_));
   XNOR2_X1 mult_93_U179 (.A(b0[6]),
	.B(b0[5]),
	.ZN(mult_93_n230));
   XNOR2_X1 mult_93_U178 (.A(b0[2]),
	.B(b0[1]),
	.ZN(mult_93_n235));
   XNOR2_X1 mult_93_U177 (.A(b0[4]),
	.B(b0[3]),
	.ZN(mult_93_n242));
   INV_X1 mult_93_U176 (.A(FE_OFN2_mult_93_n235),
	.ZN(mult_93_n225));
   INV_X1 mult_93_U175 (.A(w[1]),
	.ZN(mult_93_n220));
   INV_X1 mult_93_U174 (.A(mult_93_n30),
	.ZN(mult_93_n210));
   INV_X1 mult_93_U173 (.A(mult_93_n240),
	.ZN(mult_93_n211));
   INV_X1 mult_93_U172 (.A(mult_93_n264),
	.ZN(mult_93_n213));
   INV_X1 mult_93_U171 (.A(mult_93_n20),
	.ZN(mult_93_n212));
   INV_X1 mult_93_U170 (.A(w[0]),
	.ZN(mult_93_n221));
   INV_X1 mult_93_U169 (.A(mult_93_n286),
	.ZN(mult_93_n214));
   INV_X1 mult_93_U168 (.A(mult_93_n254),
	.ZN(mult_93_n219));
   INV_X1 mult_93_U167 (.A(mult_93_n251),
	.ZN(mult_93_n218));
   INV_X1 mult_93_U166 (.A(mult_93_n250),
	.ZN(mult_93_n217));
   INV_X1 mult_93_U165 (.A(mult_93_n249),
	.ZN(mult_93_n216));
   INV_X1 mult_93_U164 (.A(mult_93_n248),
	.ZN(mult_93_n215));
   HA_X1 mult_93_U40 (.A(mult_93_n101),
	.B(mult_93_n109),
	.CO(mult_93_n60),
	.S(mult_93_n61));
   FA_X1 mult_93_U39 (.A(mult_93_n108),
	.B(mult_93_n93),
	.CI(mult_93_n100),
	.CO(mult_93_n58),
	.S(mult_93_n59));
   HA_X1 mult_93_U38 (.A(mult_93_n73),
	.B(mult_93_n92),
	.CO(mult_93_n56),
	.S(mult_93_n57));
   FA_X1 mult_93_U37 (.A(mult_93_n99),
	.B(mult_93_n107),
	.CI(mult_93_n57),
	.CO(mult_93_n54),
	.S(mult_93_n55));
   FA_X1 mult_93_U36 (.A(mult_93_n106),
	.B(mult_93_n84),
	.CI(mult_93_n98),
	.CO(mult_93_n52),
	.S(mult_93_n53));
   FA_X1 mult_93_U35 (.A(mult_93_n56),
	.B(mult_93_n91),
	.CI(mult_93_n53),
	.CO(mult_93_n50),
	.S(mult_93_n51));
   HA_X1 mult_93_U34 (.A(mult_93_n72),
	.B(mult_93_n83),
	.CO(mult_93_n48),
	.S(mult_93_n49));
   FA_X1 mult_93_U33 (.A(mult_93_n90),
	.B(mult_93_n105),
	.CI(mult_93_n97),
	.CO(mult_93_n46),
	.S(mult_93_n47));
   FA_X1 mult_93_U32 (.A(mult_93_n52),
	.B(mult_93_n49),
	.CI(mult_93_n47),
	.CO(mult_93_n44),
	.S(mult_93_n45));
   HA_X1 mult_93_U31 (.A(mult_93_n82),
	.B(mult_93_n89),
	.CO(mult_93_n42),
	.S(mult_93_n43));
   FA_X1 mult_93_U30 (.A(mult_93_n96),
	.B(mult_93_n104),
	.CI(mult_93_n48),
	.CO(mult_93_n40),
	.S(mult_93_n41));
   FA_X1 mult_93_U29 (.A(mult_93_n46),
	.B(mult_93_n43),
	.CI(mult_93_n41),
	.CO(mult_93_n38),
	.S(mult_93_n39));
   FA_X1 mult_93_U26 (.A(mult_93_n214),
	.B(mult_93_n88),
	.CI(mult_93_n42),
	.CO(mult_93_n34),
	.S(mult_93_n35));
   FA_X1 mult_93_U25 (.A(mult_93_n40),
	.B(mult_93_n37),
	.CI(mult_93_n35),
	.CO(mult_93_n32),
	.S(mult_93_n33));
   FA_X1 mult_93_U23 (.A(mult_93_n80),
	.B(mult_93_n87),
	.CI(mult_93_n210),
	.CO(mult_93_n28),
	.S(mult_93_n29));
   FA_X1 mult_93_U22 (.A(mult_93_n34),
	.B(mult_93_n36),
	.CI(mult_93_n29),
	.CO(mult_93_n26),
	.S(mult_93_n27));
   FA_X1 mult_93_U21 (.A(mult_93_n86),
	.B(mult_93_n30),
	.CI(mult_93_n211),
	.CO(mult_93_n24),
	.S(mult_93_n25));
   FA_X1 mult_93_U20 (.A(mult_93_n28),
	.B(mult_93_n79),
	.CI(mult_93_n25),
	.CO(mult_93_n22),
	.S(mult_93_n23));
   FA_X1 mult_93_U18 (.A(mult_93_n212),
	.B(mult_93_n78),
	.CI(mult_93_n24),
	.CO(mult_93_n18),
	.S(mult_93_n19));
   FA_X1 mult_93_U17 (.A(mult_93_n77),
	.B(mult_93_n20),
	.CI(mult_93_n213),
	.CO(mult_93_n16),
	.S(mult_93_n17));
   FA_X1 mult_93_U9 (.A(mult_93_n45),
	.B(mult_93_n50),
	.CI(mult_93_n215),
	.CO(mult_93_n8),
	.S(ff_tmp_7_));
   FA_X1 mult_93_U8 (.A(mult_93_n39),
	.B(mult_93_n44),
	.CI(mult_93_n8),
	.CO(mult_93_n7),
	.S(ff_tmp_8_));
   FA_X1 mult_93_U7 (.A(mult_93_n33),
	.B(mult_93_n38),
	.CI(mult_93_n7),
	.CO(mult_93_n6),
	.S(ff_tmp_9_));
   FA_X1 mult_93_U6 (.A(mult_93_n27),
	.B(mult_93_n32),
	.CI(mult_93_n6),
	.CO(mult_93_n5),
	.S(ff_tmp_10_));
   FA_X1 mult_93_U5 (.A(mult_93_n23),
	.B(mult_93_n26),
	.CI(mult_93_n5),
	.CO(mult_93_n4),
	.S(ff_tmp_11_));
   FA_X1 mult_93_U4 (.A(mult_93_n19),
	.B(mult_93_n22),
	.CI(mult_93_n4),
	.CO(mult_93_n3),
	.S(ff_tmp_12_));
   FA_X1 mult_93_U3 (.A(mult_93_n18),
	.B(mult_93_n17),
	.CI(mult_93_n3),
	.CO(mult_93_n2),
	.S(ff_tmp_13_));
   XOR2_X1 add_97_U2 (.A(m2_tmp_7_),
	.B(ff_tmp_7_),
	.Z(s1[0]));
   AND2_X1 add_97_U1 (.A1(m2_tmp_7_),
	.A2(ff_tmp_7_),
	.ZN(add_97_n1));
   FA_X1 add_97_U1_1 (.A(ff_tmp_8_),
	.B(m2_tmp_8_),
	.CI(add_97_n1),
	.CO(add_97_carry[2]),
	.S(s1[1]));
   FA_X1 add_97_U1_2 (.A(ff_tmp_9_),
	.B(m2_tmp_9_),
	.CI(add_97_carry[2]),
	.CO(add_97_carry[3]),
	.S(s1[2]));
   FA_X1 add_97_U1_3 (.A(ff_tmp_10_),
	.B(m2_tmp_10_),
	.CI(add_97_carry[3]),
	.CO(add_97_carry[4]),
	.S(s1[3]));
   FA_X1 add_97_U1_4 (.A(ff_tmp_11_),
	.B(m2_tmp_11_),
	.CI(add_97_carry[4]),
	.CO(add_97_carry[5]),
	.S(s1[4]));
   FA_X1 add_97_U1_5 (.A(ff_tmp_12_),
	.B(m2_tmp_12_),
	.CI(add_97_carry[5]),
	.CO(add_97_carry[6]),
	.S(s1[5]));
   FA_X1 add_97_U1_6 (.A(ff_tmp_13_),
	.B(m2_tmp_13_),
	.CI(add_97_carry[6]),
	.CO(add_97_carry[7]),
	.S(s1[6]));
   FA_X1 add_97_U1_7 (.A(ff_tmp_14_),
	.B(m2_tmp_14_),
	.CI(add_97_carry[7]),
	.S(s1[7]));
   XOR2_X1 mult_90_U284 (.A(a1[2]),
	.B(a1[1]),
	.Z(mult_90_n290));
   NAND2_X1 mult_90_U283 (.A1(a1[1]),
	.A2(mult_90_n231),
	.ZN(mult_90_n272));
   XNOR2_X1 mult_90_U282 (.A(tmpfb[2]),
	.B(a1[1]),
	.ZN(mult_90_n271));
   OAI22_X1 mult_90_U281 (.A1(tmpfb[1]),
	.A2(mult_90_n272),
	.B1(mult_90_n271),
	.B2(mult_90_n231),
	.ZN(mult_90_n295));
   NAND2_X1 mult_90_U280 (.A1(mult_90_n290),
	.A2(mult_90_n295),
	.ZN(mult_90_n293));
   NAND3_X1 mult_90_U279 (.A1(mult_90_n295),
	.A2(FE_DBTN0_tmpfb_1),
	.A3(a1[1]),
	.ZN(mult_90_n294));
   MUX2_X1 mult_90_U278 (.A(mult_90_n293),
	.B(mult_90_n294),
	.S(FE_DBTN1_tmpfb_0),
	.Z(mult_90_n292));
   XNOR2_X1 mult_90_U277 (.A(mult_90_n227),
	.B(a1[2]),
	.ZN(mult_90_n291));
   NAND2_X1 mult_90_U276 (.A1(mult_90_n229),
	.A2(mult_90_n291),
	.ZN(mult_90_n238));
   NAND3_X1 mult_90_U275 (.A1(mult_90_n290),
	.A2(FE_DBTN1_tmpfb_0),
	.A3(a1[3]),
	.ZN(mult_90_n289));
   OAI21_X1 mult_90_U274 (.A(mult_90_n289),
	.B1(mult_90_n227),
	.B2(mult_90_n238),
	.ZN(mult_90_n288));
   AOI222_X1 mult_90_U273 (.A1(mult_90_n228),
	.A2(mult_90_n63),
	.B1(mult_90_n288),
	.B2(mult_90_n228),
	.C1(mult_90_n288),
	.C2(mult_90_n63),
	.ZN(mult_90_n287));
   OAI222_X1 mult_90_U272 (.A1(mult_90_n287),
	.A2(mult_90_n223),
	.B1(mult_90_n287),
	.B2(mult_90_n226),
	.C1(mult_90_n226),
	.C2(mult_90_n223),
	.ZN(mult_90_n286));
   AOI222_X1 mult_90_U271 (.A1(mult_90_n286),
	.A2(mult_90_n57),
	.B1(mult_90_n286),
	.B2(mult_90_n60),
	.C1(mult_90_n60),
	.C2(mult_90_n57),
	.ZN(mult_90_n285));
   OAI222_X1 mult_90_U270 (.A1(mult_90_n285),
	.A2(mult_90_n218),
	.B1(mult_90_n285),
	.B2(mult_90_n219),
	.C1(mult_90_n219),
	.C2(mult_90_n218),
	.ZN(mult_90_n10));
   XNOR2_X1 mult_90_U269 (.A(tmpfb[4]),
	.B(a1[3]),
	.ZN(mult_90_n284));
   XNOR2_X1 mult_90_U268 (.A(tmpfb[5]),
	.B(a1[3]),
	.ZN(mult_90_n237));
   OAI22_X1 mult_90_U267 (.A1(mult_90_n284),
	.A2(mult_90_n238),
	.B1(mult_90_n229),
	.B2(mult_90_n237),
	.ZN(mult_90_n100));
   XNOR2_X1 mult_90_U266 (.A(tmpfb[3]),
	.B(a1[3]),
	.ZN(mult_90_n283));
   OAI22_X1 mult_90_U265 (.A1(mult_90_n283),
	.A2(mult_90_n238),
	.B1(mult_90_n229),
	.B2(mult_90_n284),
	.ZN(mult_90_n101));
   XNOR2_X1 mult_90_U264 (.A(tmpfb[2]),
	.B(a1[3]),
	.ZN(mult_90_n282));
   OAI22_X1 mult_90_U263 (.A1(mult_90_n282),
	.A2(mult_90_n238),
	.B1(mult_90_n229),
	.B2(mult_90_n283),
	.ZN(mult_90_n102));
   XNOR2_X1 mult_90_U262 (.A(tmpfb[1]),
	.B(a1[3]),
	.ZN(mult_90_n281));
   OAI22_X1 mult_90_U261 (.A1(mult_90_n281),
	.A2(mult_90_n238),
	.B1(mult_90_n229),
	.B2(mult_90_n282),
	.ZN(mult_90_n103));
   XNOR2_X1 mult_90_U260 (.A(tmpfb[0]),
	.B(a1[3]),
	.ZN(mult_90_n280));
   OAI22_X1 mult_90_U259 (.A1(mult_90_n280),
	.A2(mult_90_n238),
	.B1(mult_90_n229),
	.B2(mult_90_n281),
	.ZN(mult_90_n104));
   XNOR2_X1 mult_90_U258 (.A(tmpfb[8]),
	.B(a1[1]),
	.ZN(mult_90_n278));
   XNOR2_X1 mult_90_U256 (.A(tmpfb[7]),
	.B(a1[1]),
	.ZN(mult_90_n277));
   OAI22_X1 mult_90_U255 (.A1(mult_90_n277),
	.A2(mult_90_n272),
	.B1(mult_90_n278),
	.B2(mult_90_n231),
	.ZN(mult_90_n107));
   XNOR2_X1 mult_90_U254 (.A(tmpfb[6]),
	.B(a1[1]),
	.ZN(mult_90_n276));
   OAI22_X1 mult_90_U253 (.A1(mult_90_n276),
	.A2(mult_90_n272),
	.B1(mult_90_n277),
	.B2(mult_90_n231),
	.ZN(mult_90_n108));
   XNOR2_X1 mult_90_U252 (.A(tmpfb[5]),
	.B(a1[1]),
	.ZN(mult_90_n275));
   OAI22_X1 mult_90_U251 (.A1(mult_90_n275),
	.A2(mult_90_n272),
	.B1(mult_90_n276),
	.B2(mult_90_n231),
	.ZN(mult_90_n109));
   XNOR2_X1 mult_90_U250 (.A(tmpfb[4]),
	.B(a1[1]),
	.ZN(mult_90_n274));
   OAI22_X1 mult_90_U249 (.A1(mult_90_n274),
	.A2(mult_90_n272),
	.B1(mult_90_n275),
	.B2(mult_90_n231),
	.ZN(mult_90_n110));
   XNOR2_X1 mult_90_U248 (.A(tmpfb[3]),
	.B(a1[1]),
	.ZN(mult_90_n273));
   OAI22_X1 mult_90_U247 (.A1(mult_90_n273),
	.A2(mult_90_n272),
	.B1(mult_90_n274),
	.B2(mult_90_n231),
	.ZN(mult_90_n111));
   OAI22_X1 mult_90_U246 (.A1(mult_90_n271),
	.A2(mult_90_n272),
	.B1(mult_90_n273),
	.B2(mult_90_n231),
	.ZN(mult_90_n112));
   XOR2_X1 mult_90_U245 (.A(tmpfb[7]),
	.B(a1[7]),
	.Z(mult_90_n263));
   XNOR2_X1 mult_90_U244 (.A(mult_90_n215),
	.B(a1[6]),
	.ZN(mult_90_n270));
   NAND2_X1 mult_90_U243 (.A1(mult_90_n254),
	.A2(mult_90_n270),
	.ZN(mult_90_n256));
   XNOR2_X1 mult_90_U242 (.A(tmpfb[8]),
	.B(mult_90_n215),
	.ZN(mult_90_n236));
   AOI22_X1 mult_90_U241 (.A1(mult_90_n263),
	.A2(mult_90_n214),
	.B1(mult_90_n217),
	.B2(mult_90_n236),
	.ZN(mult_90_n17));
   XNOR2_X1 mult_90_U240 (.A(tmpfb[7]),
	.B(a1[5]),
	.ZN(mult_90_n251));
   XNOR2_X1 mult_90_U239 (.A(mult_90_n222),
	.B(a1[4]),
	.ZN(mult_90_n269));
   NAND2_X1 mult_90_U238 (.A1(mult_90_n242),
	.A2(mult_90_n269),
	.ZN(mult_90_n244));
   XNOR2_X1 mult_90_U237 (.A(tmpfb[8]),
	.B(a1[5]),
	.ZN(mult_90_n253));
   OAI22_X1 mult_90_U236 (.A1(mult_90_n251),
	.A2(mult_90_n244),
	.B1(mult_90_n242),
	.B2(mult_90_n253),
	.ZN(mult_90_n22));
   XNOR2_X1 mult_90_U235 (.A(tmpfb[7]),
	.B(a1[3]),
	.ZN(mult_90_n268));
   XNOR2_X1 mult_90_U234 (.A(tmpfb[8]),
	.B(a1[3]),
	.ZN(mult_90_n241));
   OAI22_X1 mult_90_U233 (.A1(mult_90_n268),
	.A2(mult_90_n238),
	.B1(mult_90_n229),
	.B2(mult_90_n241),
	.ZN(mult_90_n32));
   XNOR2_X1 mult_90_U232 (.A(tmpfb[2]),
	.B(a1[7]),
	.ZN(mult_90_n258));
   XNOR2_X1 mult_90_U231 (.A(tmpfb[3]),
	.B(a1[7]),
	.ZN(mult_90_n259));
   OAI22_X1 mult_90_U230 (.A1(mult_90_n258),
	.A2(mult_90_n256),
	.B1(mult_90_n254),
	.B2(mult_90_n259),
	.ZN(mult_90_n266));
   XNOR2_X1 mult_90_U229 (.A(tmpfb[6]),
	.B(a1[3]),
	.ZN(mult_90_n239));
   OAI22_X1 mult_90_U228 (.A1(mult_90_n239),
	.A2(mult_90_n238),
	.B1(mult_90_n229),
	.B2(mult_90_n268),
	.ZN(mult_90_n267));
   OR2_X1 mult_90_U227 (.A1(mult_90_n266),
	.A2(mult_90_n267),
	.ZN(mult_90_n38));
   XNOR2_X1 mult_90_U226 (.A(mult_90_n266),
	.B(mult_90_n267),
	.ZN(mult_90_n39));
   NAND3_X1 mult_90_U225 (.A1(mult_90_n217),
	.A2(FE_DBTN1_tmpfb_0),
	.A3(a1[7]),
	.ZN(mult_90_n265));
   OAI21_X1 mult_90_U224 (.A(mult_90_n265),
	.B1(mult_90_n215),
	.B2(mult_90_n256),
	.ZN(mult_90_n75));
   OR3_X1 mult_90_U223 (.A1(mult_90_n242),
	.A2(tmpfb[0]),
	.A3(mult_90_n222),
	.ZN(mult_90_n264));
   OAI21_X1 mult_90_U222 (.A(mult_90_n264),
	.B1(mult_90_n222),
	.B2(mult_90_n244),
	.ZN(mult_90_n76));
   XNOR2_X1 mult_90_U221 (.A(tmpfb[6]),
	.B(a1[7]),
	.ZN(mult_90_n262));
   OAI22_X1 mult_90_U220 (.A1(mult_90_n262),
	.A2(mult_90_n256),
	.B1(mult_90_n254),
	.B2(mult_90_n216),
	.ZN(mult_90_n80));
   XNOR2_X1 mult_90_U219 (.A(tmpfb[5]),
	.B(a1[7]),
	.ZN(mult_90_n261));
   OAI22_X1 mult_90_U218 (.A1(mult_90_n261),
	.A2(mult_90_n256),
	.B1(mult_90_n254),
	.B2(mult_90_n262),
	.ZN(mult_90_n81));
   XNOR2_X1 mult_90_U217 (.A(tmpfb[4]),
	.B(a1[7]),
	.ZN(mult_90_n260));
   OAI22_X1 mult_90_U216 (.A1(mult_90_n260),
	.A2(mult_90_n256),
	.B1(mult_90_n254),
	.B2(mult_90_n261),
	.ZN(mult_90_n82));
   OAI22_X1 mult_90_U215 (.A1(mult_90_n259),
	.A2(mult_90_n256),
	.B1(mult_90_n254),
	.B2(mult_90_n260),
	.ZN(mult_90_n83));
   XNOR2_X1 mult_90_U214 (.A(tmpfb[1]),
	.B(a1[7]),
	.ZN(mult_90_n257));
   OAI22_X1 mult_90_U213 (.A1(mult_90_n257),
	.A2(mult_90_n256),
	.B1(mult_90_n254),
	.B2(mult_90_n258),
	.ZN(mult_90_n85));
   XNOR2_X1 mult_90_U212 (.A(tmpfb[0]),
	.B(a1[7]),
	.ZN(mult_90_n255));
   OAI22_X1 mult_90_U211 (.A1(mult_90_n255),
	.A2(mult_90_n256),
	.B1(mult_90_n254),
	.B2(mult_90_n257),
	.ZN(mult_90_n86));
   NOR2_X1 mult_90_U210 (.A1(mult_90_n254),
	.A2(FE_DBTN1_tmpfb_0),
	.ZN(mult_90_n87));
   XNOR2_X1 mult_90_U208 (.A(tmpfb[6]),
	.B(a1[5]),
	.ZN(mult_90_n250));
   OAI22_X1 mult_90_U207 (.A1(mult_90_n250),
	.A2(mult_90_n244),
	.B1(mult_90_n242),
	.B2(mult_90_n251),
	.ZN(mult_90_n89));
   XNOR2_X1 mult_90_U206 (.A(tmpfb[5]),
	.B(a1[5]),
	.ZN(mult_90_n249));
   OAI22_X1 mult_90_U205 (.A1(mult_90_n249),
	.A2(mult_90_n244),
	.B1(mult_90_n242),
	.B2(mult_90_n250),
	.ZN(mult_90_n90));
   XNOR2_X1 mult_90_U204 (.A(tmpfb[4]),
	.B(a1[5]),
	.ZN(mult_90_n248));
   OAI22_X1 mult_90_U203 (.A1(mult_90_n248),
	.A2(mult_90_n244),
	.B1(mult_90_n242),
	.B2(mult_90_n249),
	.ZN(mult_90_n91));
   XNOR2_X1 mult_90_U202 (.A(tmpfb[3]),
	.B(a1[5]),
	.ZN(mult_90_n247));
   OAI22_X1 mult_90_U201 (.A1(mult_90_n247),
	.A2(mult_90_n244),
	.B1(mult_90_n242),
	.B2(mult_90_n248),
	.ZN(mult_90_n92));
   XNOR2_X1 mult_90_U200 (.A(tmpfb[2]),
	.B(a1[5]),
	.ZN(mult_90_n246));
   OAI22_X1 mult_90_U199 (.A1(mult_90_n246),
	.A2(mult_90_n244),
	.B1(mult_90_n242),
	.B2(mult_90_n247),
	.ZN(mult_90_n93));
   XNOR2_X1 mult_90_U198 (.A(tmpfb[1]),
	.B(a1[5]),
	.ZN(mult_90_n245));
   OAI22_X1 mult_90_U197 (.A1(mult_90_n245),
	.A2(mult_90_n244),
	.B1(mult_90_n242),
	.B2(mult_90_n246),
	.ZN(mult_90_n94));
   XNOR2_X1 mult_90_U196 (.A(tmpfb[0]),
	.B(a1[5]),
	.ZN(mult_90_n243));
   OAI22_X1 mult_90_U195 (.A1(mult_90_n243),
	.A2(mult_90_n244),
	.B1(mult_90_n242),
	.B2(mult_90_n245),
	.ZN(mult_90_n95));
   NOR2_X1 mult_90_U194 (.A1(mult_90_n242),
	.A2(FE_DBTN1_tmpfb_0),
	.ZN(mult_90_n96));
   OAI22_X1 mult_90_U192 (.A1(mult_90_n237),
	.A2(mult_90_n238),
	.B1(mult_90_n229),
	.B2(mult_90_n239),
	.ZN(mult_90_n99));
   XOR2_X1 mult_90_U190 (.A(mult_90_n2),
	.B(mult_90_n235),
	.Z(mult_90_n234));
   XNOR2_X1 mult_90_U189 (.A(mult_90_n17),
	.B(mult_90_n234),
	.ZN(m1_tmp_15_));
   INV_X1 mult_90_U188 (.A(a1[7]),
	.ZN(mult_90_n215));
   XOR2_X1 mult_90_U186 (.A(a1[6]),
	.B(mult_90_n222),
	.Z(mult_90_n254));
   INV_X1 mult_90_U185 (.A(a1[3]),
	.ZN(mult_90_n227));
   INV_X1 mult_90_U184 (.A(a1[5]),
	.ZN(mult_90_n222));
   INV_X1 mult_90_U182 (.A(a1[0]),
	.ZN(mult_90_n231));
   XOR2_X2 mult_90_U181 (.A(a1[4]),
	.B(mult_90_n227),
	.Z(mult_90_n242));
   INV_X1 mult_90_U180 (.A(mult_90_n256),
	.ZN(mult_90_n214));
   INV_X1 mult_90_U179 (.A(mult_90_n254),
	.ZN(mult_90_n217));
   INV_X1 mult_90_U178 (.A(mult_90_n32),
	.ZN(mult_90_n224));
   INV_X1 mult_90_U177 (.A(mult_90_n240),
	.ZN(mult_90_n225));
   INV_X1 mult_90_U176 (.A(mult_90_n279),
	.ZN(mult_90_n230));
   INV_X1 mult_90_U175 (.A(mult_90_n263),
	.ZN(mult_90_n216));
   INV_X1 mult_90_U174 (.A(mult_90_n252),
	.ZN(mult_90_n221));
   INV_X1 mult_90_U173 (.A(mult_90_n22),
	.ZN(mult_90_n220));
   INV_X1 mult_90_U172 (.A(mult_90_n290),
	.ZN(mult_90_n229));
   INV_X1 mult_90_U171 (.A(mult_90_n292),
	.ZN(mult_90_n228));
   INV_X1 mult_90_U170 (.A(mult_90_n61),
	.ZN(mult_90_n223));
   INV_X1 mult_90_U169 (.A(mult_90_n62),
	.ZN(mult_90_n226));
   INV_X1 mult_90_U168 (.A(mult_90_n53),
	.ZN(mult_90_n218));
   INV_X1 mult_90_U167 (.A(mult_90_n56),
	.ZN(mult_90_n219));
   HA_X1 mult_90_U41 (.A(mult_90_n104),
	.B(mult_90_n112),
	.CO(mult_90_n62),
	.S(mult_90_n63));
   FA_X1 mult_90_U40 (.A(mult_90_n111),
	.B(mult_90_n96),
	.CI(mult_90_n103),
	.CO(mult_90_n60),
	.S(mult_90_n61));
   HA_X1 mult_90_U39 (.A(mult_90_n76),
	.B(mult_90_n95),
	.CO(mult_90_n58),
	.S(mult_90_n59));
   FA_X1 mult_90_U38 (.A(mult_90_n102),
	.B(mult_90_n110),
	.CI(mult_90_n59),
	.CO(mult_90_n56),
	.S(mult_90_n57));
   FA_X1 mult_90_U37 (.A(mult_90_n109),
	.B(mult_90_n87),
	.CI(mult_90_n101),
	.CO(mult_90_n54),
	.S(mult_90_n55));
   FA_X1 mult_90_U36 (.A(mult_90_n58),
	.B(mult_90_n94),
	.CI(mult_90_n55),
	.CO(mult_90_n52),
	.S(mult_90_n53));
   HA_X1 mult_90_U35 (.A(mult_90_n75),
	.B(mult_90_n86),
	.CO(mult_90_n50),
	.S(mult_90_n51));
   FA_X1 mult_90_U34 (.A(mult_90_n93),
	.B(mult_90_n108),
	.CI(mult_90_n100),
	.CO(mult_90_n48),
	.S(mult_90_n49));
   FA_X1 mult_90_U33 (.A(mult_90_n54),
	.B(mult_90_n51),
	.CI(mult_90_n49),
	.CO(mult_90_n46),
	.S(mult_90_n47));
   HA_X1 mult_90_U32 (.A(mult_90_n85),
	.B(mult_90_n92),
	.CO(mult_90_n44),
	.S(mult_90_n45));
   FA_X1 mult_90_U31 (.A(mult_90_n99),
	.B(mult_90_n107),
	.CI(mult_90_n50),
	.CO(mult_90_n42),
	.S(mult_90_n43));
   FA_X1 mult_90_U30 (.A(mult_90_n48),
	.B(mult_90_n45),
	.CI(mult_90_n43),
	.CO(mult_90_n40),
	.S(mult_90_n41));
   FA_X1 mult_90_U27 (.A(mult_90_n230),
	.B(mult_90_n91),
	.CI(mult_90_n44),
	.CO(mult_90_n36),
	.S(mult_90_n37));
   FA_X1 mult_90_U26 (.A(mult_90_n42),
	.B(mult_90_n39),
	.CI(mult_90_n37),
	.CO(mult_90_n34),
	.S(mult_90_n35));
   FA_X1 mult_90_U24 (.A(mult_90_n83),
	.B(mult_90_n90),
	.CI(mult_90_n224),
	.CO(mult_90_n30),
	.S(mult_90_n31));
   FA_X1 mult_90_U23 (.A(mult_90_n36),
	.B(mult_90_n38),
	.CI(mult_90_n31),
	.CO(mult_90_n28),
	.S(mult_90_n29));
   FA_X1 mult_90_U22 (.A(mult_90_n89),
	.B(mult_90_n32),
	.CI(mult_90_n225),
	.CO(mult_90_n26),
	.S(mult_90_n27));
   FA_X1 mult_90_U21 (.A(mult_90_n30),
	.B(mult_90_n82),
	.CI(mult_90_n27),
	.CO(mult_90_n24),
	.S(mult_90_n25));
   FA_X1 mult_90_U19 (.A(mult_90_n220),
	.B(mult_90_n81),
	.CI(mult_90_n26),
	.CO(mult_90_n20),
	.S(mult_90_n21));
   FA_X1 mult_90_U18 (.A(mult_90_n80),
	.B(mult_90_n22),
	.CI(mult_90_n221),
	.CO(mult_90_n18),
	.S(mult_90_n19));
   FA_X1 mult_90_U10 (.A(mult_90_n47),
	.B(mult_90_n52),
	.CI(mult_90_n10),
	.CO(mult_90_n9),
	.S(m1_tmp_7_));
   FA_X1 mult_90_U9 (.A(mult_90_n41),
	.B(mult_90_n46),
	.CI(mult_90_n9),
	.CO(mult_90_n8),
	.S(m1_tmp_8_));
   FA_X1 mult_90_U8 (.A(mult_90_n35),
	.B(mult_90_n40),
	.CI(mult_90_n8),
	.CO(mult_90_n7),
	.S(m1_tmp_9_));
   FA_X1 mult_90_U7 (.A(mult_90_n29),
	.B(mult_90_n34),
	.CI(mult_90_n7),
	.CO(mult_90_n6),
	.S(m1_tmp_10_));
   FA_X1 mult_90_U6 (.A(mult_90_n25),
	.B(mult_90_n28),
	.CI(mult_90_n6),
	.CO(mult_90_n5),
	.S(m1_tmp_11_));
   FA_X1 mult_90_U5 (.A(mult_90_n21),
	.B(mult_90_n24),
	.CI(mult_90_n5),
	.CO(mult_90_n4),
	.S(m1_tmp_12_));
   FA_X1 mult_90_U4 (.A(mult_90_n20),
	.B(mult_90_n19),
	.CI(mult_90_n4),
	.CO(mult_90_n3),
	.S(m1_tmp_13_));
   FA_X1 mult_90_U3 (.A(mult_90_n18),
	.B(mult_90_n17),
	.CI(mult_90_n3),
	.CO(mult_90_n2),
	.S(m1_tmp_14_));
   XNOR2_X1 sub_92_U12 (.A(sub_92_n10),
	.B(tmpDin[0]),
	.ZN(w[0]));
   INV_X1 sub_92_U11 (.A(m1_tmp_14_),
	.ZN(sub_92_n3));
   INV_X1 sub_92_U10 (.A(m1_tmp_12_),
	.ZN(sub_92_n5));
   INV_X1 sub_92_U9 (.A(m1_tmp_11_),
	.ZN(sub_92_n6));
   INV_X1 sub_92_U8 (.A(m1_tmp_10_),
	.ZN(sub_92_n7));
   INV_X1 sub_92_U7 (.A(m1_tmp_9_),
	.ZN(sub_92_n8));
   INV_X1 sub_92_U6 (.A(tmpDin[0]),
	.ZN(sub_92_n1));
   INV_X1 sub_92_U5 (.A(m1_tmp_8_),
	.ZN(sub_92_n9));
   NAND2_X1 sub_92_U4 (.A1(m1_tmp_7_),
	.A2(sub_92_n1),
	.ZN(sub_92_carry[1]));
   INV_X1 sub_92_U3 (.A(m1_tmp_13_),
	.ZN(sub_92_n4));
   INV_X1 sub_92_U2 (.A(m1_tmp_15_),
	.ZN(sub_92_n2));
   INV_X1 sub_92_U1 (.A(m1_tmp_7_),
	.ZN(sub_92_n10));
   FA_X1 sub_92_U2_1 (.A(tmpDin[1]),
	.B(sub_92_n9),
	.CI(sub_92_carry[1]),
	.CO(sub_92_carry[2]),
	.S(w[1]));
   FA_X1 sub_92_U2_2 (.A(tmpDin[2]),
	.B(sub_92_n8),
	.CI(sub_92_carry[2]),
	.CO(sub_92_carry[3]),
	.S(w[2]));
   FA_X1 sub_92_U2_3 (.A(tmpDin[3]),
	.B(sub_92_n7),
	.CI(sub_92_carry[3]),
	.CO(sub_92_carry[4]),
	.S(w[3]));
   FA_X1 sub_92_U2_4 (.A(tmpDin[4]),
	.B(sub_92_n6),
	.CI(sub_92_carry[4]),
	.CO(sub_92_carry[5]),
	.S(w[4]));
   FA_X1 sub_92_U2_5 (.A(tmpDin[5]),
	.B(sub_92_n5),
	.CI(sub_92_carry[5]),
	.CO(sub_92_carry[6]),
	.S(w[5]));
   FA_X1 sub_92_U2_6 (.A(tmpDin[6]),
	.B(sub_92_n4),
	.CI(sub_92_carry[6]),
	.CO(sub_92_carry[7]),
	.S(w[6]));
   FA_X1 sub_92_U2_7 (.A(tmpDin[7]),
	.B(sub_92_n3),
	.CI(sub_92_carry[7]),
	.CO(sub_92_carry[8]),
	.S(w[7]));
   FA_X1 sub_92_U2_8 (.A(tmpDin[7]),
	.B(sub_92_n2),
	.CI(sub_92_carry[8]),
	.S(w[8]));
endmodule

